### ISSUE TITLE
Where is the configuration?

### ISSUE THREAD

**Issue by mbnoimi** [RealRaven2000/FiltaQuilla#103]
After installing FiltaQuilla I couldn't figure out where can I find the configuration!
![image](https://user-images.githubusercontent.com/284547/115511244-4bbf9c80-a289-11eb-9a76-d9f80c27fda1.png)
![image](https://user-images.githubusercontent.com/284547/115510992-0307e380-a289-11eb-88e2-d600387f36e4.png)
* TB 78.7.1 (64-bit) 
* FQ 3.1

**Comment by RealRaven2000** [comment]
As of [version 3.1](https://quickfilters.quickfolders.org/fq-versions.html#3.1), you can now access FiltaQuilla's settings from the 3 dot menu:

![image](https://user-images.githubusercontent.com/6314674/111152068-38355d80-8588-11eb-9128-d434bd11ab69.png)

I am using John Bieling's Window Loader experimental API and he updated it to be more conform with other Add-ons from Thunderbird 78 going forward. Same change will be applied to all my Add-ons, so eventually the Tools / Add-ons menu is going away. (We can't have both ways).

See also #89

**Comment by mbnoimi** [comment]
![image](https://user-images.githubusercontent.com/284547/115567270-c1e0f500-a2c3-11eb-9d69-382db58b8d0d.png)

**Comment by RealRaven2000** [comment]
> ![image](https://user-images.githubusercontent.com/284547/115567270-c1e0f500-a2c3-11eb-9d69-382db58b8d0d.png)
> 
> As you saw, I'm unable to access **Options**

Can you try an update Thunderbird to the current version (78.10) - the function is provided by John Bieling's WindowListener experiment so I don't know why it isn't there. What other Add-ons are installed?

**Comment by RealRaven2000** [comment]
I asked the author John and he said he had seen this as intermittent behavior that should be solvable by restarting Thunderbird, can you try that next?

**Comment by mbnoimi** [comment]
> I asked the author John and he said he had seen this as intermittent behavior that should be solvable by restarting

Works
