### ISSUE TITLE
Some help content invisible in dark mode

### ISSUE THREAD

**Issue by LorenAmelang** [RealRaven2000/FiltaQuilla#104]
In TBird 78.10.0 set to inherit dark mode from Windows 10, and the Dark Reader extension for content, the help screenshots and some of the text at
  https://quickfilters.quickfolders.org/filtaquilla.html#save_attachment
show nicely, but then there is just a lot of blank area. Once I noticed the very pale text, I found I could drag to select it, then it is visible:

![2021-05-01](https://user-images.githubusercontent.com/1297090/116793555-47129980-aa7c-11eb-8552-0c084eef6ed3.png)

Yes, all of that blue text was as pale as the part following "Read" when unselected. 

In mail messages when this happens, a different choice in the Allow HTML Temp extension usually helps. Here it makes no difference. I know dark modes are a minefield, but this one seems unusual. Disabling Dark Reader and reloading the page makes no difference. 

Vivaldi with the same "Dark Reader" extension as TBird shows it readable: 

![FqViv](https://user-images.githubusercontent.com/1297090/116793774-aa50fb80-aa7d-11eb-8fbe-005a09f56b0c.JPG)

**Comment by LorenAmelang** [comment]
OK, it gets stranger...  After my test of disabling Dark Reader in TBird and reloading the invisible page, it was still as invisible. I re-enabled Dark Reader, closed the Add-Ons tab, and there was the help page, nicely rendered exactly like the Vivaldi version! Without intentionally reloading it! 

I tried to test other URLs in that window, but it looks like we can't just insert our own. Somehow your original help call bypassed Dark Reader? And was mostly invisible without it?

**Comment by RealRaven2000** [comment]
the help page is a website (so it's not a HTML page contained within the
Add-on) if you right-click the page and choose view in web browser, what do
you see?

the Theme should not change the way any Web pages are displayed... OTTOH
if you have a screen reader Add-on installed behaviour becomes less
predictable. I will look into whether I can change the css rules so it's
less problematic if I can reproduce it.

**Comment by RealRaven2000** [comment]
> OK, it gets stranger... After my test of disabling Dark Reader in TBird and reloading the invisible page, it was still as invisible. I re-enabled Dark Reader, closed the Add-Ons tab, and there was the help page, nicely rendered exactly like the Vivaldi version! Without intentionally reloading it!
> 
> I tried to test other URLs in that window, but it looks like we can't just insert our own. Somehow your original help call bypassed Dark Reader? And was mostly invisible without it?

Did you restart Thunderbird in between disabling the Reader Add-on? It  sometimes is difficult for Add-ons to remove injected CSS rules so a restart is already a good option when testing issues lie this.

**Comment by LorenAmelang** [comment]
No screen reader Add-on. 

Today the help page opens properly the first time in TBird, like my second screenshot, and like every other view in a browser. I did not quit and restart TBird during the pale view, but I didn't restart it before its display changed, either...  Looks like just a freak occurrence, maybe my internet glitched on a bit of CSS. And switching Dark Reader back on reloaded it? I know it inserts a ton of its own CSS into pages. 

You probably have nothing to worry about, sorry for the stress.
