### ISSUE TITLE
Body Regex Match [Enhancement request]

### ISSUE THREAD

**Issue by baconcoconut** [RealRaven2000/FiltaQuilla#11]
Thank you very much for keeping this addon going.

Any chance you can add an option for Body Regex Match?  If I recall correctly Kent James wrote on his site some time ago that it can be done. For people like me that use Thunderbird also for RSS it will be immensely useful.

**Comment by RealRaven2000** [comment]
The problem with creating a regexp on body is that it needs to parse the complete body and needs to stream it, so it may lead to unacceptable delays during "get mail" - unfortunately filter conditions in Thunderbird are currently executed synchronously . I would have to look into how the conventional "body contains" works and get back to you.

**Comment by baconcoconut** [comment]
Thanks for looking into it!

**Comment by RealRaven2000** [comment]
implemented through issue #115 in version 3.2
