### ISSUE TITLE
Body Regex Match [email has multiple bodies] TB 91.0b1 

### ISSUE THREAD

**Issue by rusak47** [RealRaven2000/FiltaQuilla#115]
Hi, recently i noticed that on some emails body regex doesn't work, i.e. finds nothing, even if body contains searched keywords.
After looking into message source, i've found that email has multiple bodies: for text/plain and text/html.
And in my case search is made only on plain part (possibly related to preferences).

```
Content-Type: multipart/alternative;
 boundary="===============4319708298361970362=="
MIME-Version: 1.0
Subject: Please Confirm Your E-mail Address
From: DowntimeBot <norepy@downtimebot.com>
Date: Thu, 29 Jul 2021 07:39:47 +0000 (UTC)
Message-ID: <162754438725.981709.8888531141846460144@downtimebot>
X-SG-EID: jPkgrrralNFzOaiC1A67TXaB4wvhaaYX/HdsPdC4viAOZpUlqAeCNg11cMe2KwEWzfPaIm8782RTll
 wKio5X/CMQw5J3uq5En3FkDuZciFsjI8YMEJM0LGgXU4aSlNFKHLYhF1AMD6g1ZKI63l8/MCn9dMBT
 E8yN635Igt+v2VjwCmHxP1pACzXfMhU6XwsLnwLcr+Xf0/oxNoaVARztYA==
X-Entity-ID: Oozrcca6znxvgrtZ9x66Wg==
X-KLMS-Rule-ID: 1
X-KLMS-Message-Action: skipped, MessageAuthentication
X-KLMS-AntiSpam-Lua-Profiles: 165306 [Jul 28 2021]
X-KLMS-AntiSpam-Version: 5.9.20.0
X-KLMS-AntiSpam-Envelope-From: bounces+5116680-31c5-.v=inbox.lv@em2368.downtimebot.com
X-KLMS-AntiSpam-Rate: 15
X-KLMS-AntiSpam-Status: not_detected
X-KLMS-AntiSpam-Method: none
X-KLMS-AntiSpam-Auth: dmarc=none header.from=downtimebot.com;spf=pass smtp.mailfrom=em2368.downtimebot.com;dkim=fail header.d=downtimebot.com
X-KLMS-AntiSpam-Info: LuaCore: 449 449 5db59deca4a4f5e6ea34a93b13bc730e229092f4, {rep_avail}, {Tracking_nm_60_70}, {Tracking_om_50_60}, {Tracking_phishing_bb, bb1}, {Prob_phishing_engines}, {Tracking_cat_phish}, {Tracking_from_domain_doesnt_match_to}, {Tracking_smtp_domain_mismatch}, ApMailHostAddress: 149.72.32.168
X-MS-Exchange-Organization-SCL: -1
X-KLMS-AntiSpam-Interceptor-Info: scan successful
X-KLMS-AntiPhishing: not scanned, disabled by settings
X-KLMS-AntiVirus: Modern antivirus of Inbox, version 8.0.3.30, bases: 2021/07/29 00:30:00 #16993260
X-KLMS-AntiVirus-Status: Clean, skipped

--===============4319708298361970362==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hi http://url6413.downtimebot.com/ls/click?upn=7v3bxd-2B8GSYgigpNBlwH-2F6A59WJ3EIKaRzad9ocHywQ-3D-IM9_kOLbtQyGKwRfioKCF5j-2B9d6vl9BDL7dudHUQEIDcBs8OZ1TYkIlonTighfM-2B45LJsz1yi-2Fs85DV1mI1gtOLplTIaUr7lXOeuWkVlzcD3rt0vCxLRt2IVFpjHoK3OVIgF1HhzLluVK-2B0EqajIV3bmimR3T6xoOHLPjj2U6c8THiPmaU8FizXU9NZNviUmnittyqSRQi7Rb76E8l3OfIZY7w-3D-3D

You're almost ready to start monitoring with DowntimeBot. Simply click the link below to verify your email address

http://url6413.downtimebot.com/ls/click?upn=NEdxAMXZfPQAcq7tkkNaghfTyozb66aByqd4yvuffxBnLUhVMBJbHd2uhEQSIUbKi-2FeHrpLHSPdFXmt4TEk8qiQM68NQWq2be3Zv-2FSVWTLfxpC5mBwECq-2BM-2FCbAfF-2FUX-2FrYc-2BhGyJc1J7MJwa5h-2Fcd5FYleV4HYckVtsTpXqWs4-3DIZJH_kOLbtQyGKwRfioKCF5j-2B9d6vl9BDL7dudHUQEIDcBs8OZ1TYkIlonTighfM-2B45LJFtY0GhSKcQthJpAdgdWYx150E8wRvnhxhUhIZY9uR5rRwlYvZLW5Sq-2FnqMckZrX6TeK3SGxOwqUA7I3P6te4JAi41EXr1pFsyF-2FcDa2X0MbCMWVcr01cVxurtBp3x4khDU-2Fq2rZZvzjZSzYbN3dN8w-3D-3D

Your DowntimeBot team
--===============4319708298361970362==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<!--[if !mso]><!-->
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<!--<![endif]-->
	<!--[if (gte mso 9)|(IE)]>
        <xml>
            <o:OfficeDocumentSettings>
                <o:AllowPNG/>
                    <o:PixelsPerInch>96</o:PixelsPerInch>
                </o:OfficeDocumentSettings>
        </xml>
        <![endif]-->
	<!--[if (gte mso 9)|(IE)]>
        <style type="text/css">
            body {width: 600px;margin: 0 auto;}
            table {border-collapse: collapse;}
            table, td {mso-table-lspace: 0pt;mso-table-rspace: 0pt;}
            img {-ms-interpolation-mode: bicubic;}
        </style>
        <![endif]-->
	<style type="text/css">
        body, p, div {
            font-family: arial, helvetica, sans-serif;
            font-size: 14px;
        }
        body {
            color: #000000;
        }
        body a {
            color: #1188E6;
            text-decoration: none;
        }
        p {
            margin: 0;
            padding: 0;
        }
        table.wrapper {
            width: 100% !important;
            table-layout: fixed;
            -webkit-font-smoothing: antialiased;
            -webkit-text-size-adjust: 100%;
            -moz-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
        }
        img.max-width {
            max-width: 100% !important;
        }
        .column.of-2 {
            width: 50%;
        }
        .column.of-3 {
            width: 33.333%;
        }
        .column.of-4 {
            width: 25%;
        }
        @media screen and (max-width:480px) {
            .preheader .rightColumnContent,
            .footer .rightColumnContent {
                text-align: left !important;
            }
            .preheader .rightColumnContent div,
            .preheader .rightColumnContent span,
            .footer .rightColumnContent div,
            .footer .rightColumnContent span {
                text-align: left !important;
            }
            .preheader .rightColumnContent,
            .preheader .leftColumnContent {
                font-size: 80% !important;
                padding: 5px 0;
            }
            table.wrapper-mobile {
                width: 100% !important;
                table-layout: fixed;
            }
            img.max-width {
                height: auto !important;
                max-width: 100% !important;
            }
            a.bulletproof-button {
                display: block !important;
                width: auto !important;
                font-size: 80%;
                padding-left: 0 !important;
                padding-right: 0 !important;
            }
            .columns {
                width: 100% !important;
            }
            .column {
                display: block !important;
                width: 100% !important;
                padding-left: 0 !important;
                padding-right: 0 !important;
                margin-left: 0 !important;
                margin-right: 0 !important;
            }
            .social-icon-column {
                display: inline-block !important;
            }
        }
	</style>
</head>

<body>
    
	<center class="wrapper" data-link-color="#1188E6" data-body-style="font-size:14px; font-family:arial,helvetica,sans-serif; color:#000000; background-color:#ffffff;">
		<div class="webkit">
			<table cellpadding="0" cellspacing="0" border="0" width="100%" class="wrapper" bgcolor="#ffffff">
				<tbody>
					<tr>
						<td valign="top" bgcolor="#ffffff" width="100%">
							<table width="100%" role="content-container" class="outer" align="center" cellpadding="0" cellspacing="0" border="0">
								<tbody>
									<tr>
										<td width="100%">
											<table width="100%" cellpadding="0" cellspacing="0" border="0">
												<tbody>
													<tr>
														<td>
															<!--[if mso]>
                                                            <center>
                                                                <table>
                                                                    <tr>
                                                                        <td width="600">
                                                            <![endif]-->
															<table width="100%" cellpadding="0" cellspacing="0" border="0" style="width:100%; max-width:600px;" align="center">
																<tbody>
																	<tr>
																		<td role="modules-container" style="padding:0px 0px 0px 0px; color:#000000; text-align:left;" bgcolor="#FFFFFF" width="100%" align="left">
																			<table class="module" role="module" data-type="text" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="21e16592-cb16-4a90-bd81-127a95c8a2f8" data-mc-module-version="2019-10-22">
																				<tbody>
																					<tr>
																						<td style="padding:18px 0px 0px 12px; line-height:14px; text-align:inherit;" height="100%" valign="top" bgcolor="" role="module-content">
																							<div>
																								<div style="font-family: inherit; text-align: inherit">Hi https://bit.ly/sexygo,</div>
																							</div>
																						</td>
																					</tr>
																				</tbody>
																			</table>
																			<table class="module" role="module" data-type="text" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;" data-muid="062aa0db-4b06-4fbb-88ac-d2e7c53ad55a" data-mc-module-version="2019-10-22">
																				<tbody>
																					<tr>
																						<td style="padding:18px 12px 18px 12px; line-height:20px; text-align:inherit;" height="100%" valign="top" bgcolor="" role="module-content">
																							<div>
																								<div style="font-family: inherit; text-align: inherit">
                                                                                                    You're almost ready to start monitoring with DowntimeBot.<br/>
                                                                                                    Simply click the button below to verify your email address
                                                                                                </div>
																							</div>
																						</td>
																					</tr>
																				</tbody>
																			</table>
																			<table border="0" cellpadding="0" cellspacing="0" class="module" data-role="module-button" data-type="button" role="module" style="table-layout:fixed;" width="100%" data-muid="0723847e-656e-4c8b-ba90-eb72c513571b">
																				<tbody>
																					<tr>
																						<td align="left" bgcolor="" class="outer-td" style="padding:18px 12px 18px 12px;">
																							<table border="0" cellpadding="0" cellspacing="0" class="wrapper-mobile" style="text-align:center;">
																								<tbody>
																									<tr>
																										<td align="center" bgcolor="#333333" class="inner-td" style="border-radius:6px; font-size:16px; text-align:left; background-color:inherit;"> <a href="http://url6413.downtimebot.com/ls/click?upn=NEdxAMXZfPQAcq7tkkNaghfTyozb66aByqd4yvuffxBnLUhVMBJbHd2uhEQSIUbKi-2FeHrpLHSPdFXmt4TEk8qiQM68NQWq2be3Zv-2FSVWTLfxpC5mBwECq-2BM-2FCbAfF-2FUX-2FrYc-2BhGyJc1J7MJwa5h-2FcYU179-2FNxIfaSAc-2Fhp1SjWI-3D2Pvx_kOLbtQyGKwRfioKCF5j-2B9d6vl9BDL7dudHUQEIDcBs8OZ1TYkIlonTighfM-2B45LJh0U3TgIiCaGW0HRuX-2FAtJIYBol4y22PKGeDh0ftAlP44Jhpoq04eDoWYsucPiFjcDj800xYfDIPTY6w-2FTnDLcEceVu-2FWEOMu5ZZz5-2BlkY9et-2FGTXyZrbE2EQSJHv3MOMsYdXdiYN-2FyamsFThKyzZ7Q-3D-3D" style="background-color:#333333; border:1px solid #333333; border-color:#333333; border-radius:6px; border-width:1px; color:#ffffff; display:inline-block; font-size:14px; font-weight:normal; letter-spacing:0px; line-height:normal; padding:12px 18px 12px 18px; text-align:center; text-decoration:none; border-style:solid;" target="_blank">Ver
 ify email address</a> </td>
																									</tr>
																								</tbody>
																							</table>
																						</td>
																					</tr>
																				</tbody>
																			</table>
																			<table class="module" role="module" data-type="text" border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed;">
																				<tbody>
																					<tr>
																						<td style="padding:18px 0px 60px 0px; line-height:22px; text-align:inherit; background-color:#fff;" height="100%" valign="top" bgcolor="#fff" role="module-content">
																							<div>
																								<div style="font-family: inherit; text-align: center"><span style="color: #222222; font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline; background-color: rgb(255, 255, 255)">Your DowntimeBot Team</span></div>
																							</div>
																						</td>
																					</tr>
																				</tbody>
																			</table>
																		</td>
																	</tr>
																</tbody>
															</table>
															<!--[if mso]>
                                                                  </td>
                                                                </tr>
                                                              </table>
                                                            </center>
                                                            <![endif]-->
														</td>
													</tr>
												</tbody>
											</table>
										</td>
									</tr>
								</tbody>
							</table>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</center>
    

<img src="http://url6413.downtimebot.com/wf/open?upn=yjCF5EnJwQUgK91H2u2hG5M-2BbEpg4YD77wUlnCFKn3stYZmpI1EDTp6PAkzoMYxTrCT002wgZheypQzCk-2BaeDcZoO7PLpjfa0Tlt08k9uf6EW7XawRS2fFp-2Bfz68M3K2s5iNEkMC55g-2FPMPSlxgDMEtOEYyXHhzRcaw5Opw-2BPk0oM0dgyTVBZA9ClfGcL9pAUyTPNs8hRvsP4HPD3MsdC3SeKYDM82ay3c-2Fwmqfv3XY-3D" alt="" width="1" height="1" border="0" style="height:1px !important;width:1px !important;border-width:0 !important;margin-top:0 !important;margin-bottom:0 !important;margin-right:0 !important;margin-left:0 !important;padding-top:0 !important;padding-bottom:0 !important;padding-right:0 !important;padding-left:0 !important;"/>
</body>
</html>

--===============4319708298361970362==--
```

**Comment by RealRaven2000** [comment]
> Hi, recently i noticed that on some emails body regex doesn't work, i.e.
> finds nothing, even if body contains searched keywords.
>
I know that's what I wrote on the comment for the Tb78 branch because the
mime parser returns the raw multipart message. it can even be based encoded
or encrypted in which v case the search will also not work.  but it should
work with the new method for Thunderbird 91. John advised me not to
reinvent the wheel and write my own MIME parser because its super
complicated.

 I think we can also not be sure whether the email body is always in the
first mime part as there aren't binding standards. it may be one of the
reasons why this was never implemented in the original Add-on.

Of course average users do not know or care about how chomped this stuff
gets and it'S usually more dangerous to offer a half working feature than
to omit it. Not sure whether we should have this unreliable regex function
in Tb78 or wait until August when 91 comes around. I am not going to
support a complicated custom mime parser as part of the Filtaquilla code
base.

**Comment by rusak47** [comment]
> I know that's what I wrote on the comment for the Tb78 branch because the mime parser returns the raw multipart message. it can even be based encoded or encrypted in which v case the search will also not work. but it should work with the new method for Thunderbird 91.

Sorry, i haven't mentioned - it's for Thunderbird 91.0b1 (64-bit) with add-on version 56.

` !found: {"regex":{},"foundBody":false,"foundSubject":false,"processed":true,"msgURI":null,"body":"Hi http://url6413.downtimebot.com/ls/click?upn=7v3bxd-2B8GSYgig…jj2U6c8THiPmaU8FizXU9NZNviUmnittyqSRQi7Rb76E8l3OfIZY7w-3D-3D\r\n\r\nYou're almost ready to start monitoring with DowntimeBot. Simply click the link below to verify your email address\r\n\r\nhttp://url6413.downtimebot.com/ls/click?upn=NEdxAMXZfPQAcq7tkkNaghfTyozb66aByqd4yvuffxBnLUhVMBJbHd2uhEQSIUbKi-2FeHrpLHSPdFXmt4TEk8qiQM68NQWq2be3Zv-2FSVWTLfxpC5mBwECq-2BM-2FCbAfF-2FUX-2FrYc-2BhGyJc1J7MJwa5h-2Fcd5FYleV4HYckVtsTpXqWs4-3DIZJH_kOLbtQyGKwRfioKCF5j-2B9d6vl9BDL7dudHUQEIDcBs8OZ1TYkIlonTighfM-2B45LJFtY0GhSKcQthJpAdgdWYx150E8wRvnhxhUhIZY9uR5rRwlYvZLW5Sq-2FnqMckZrX6TeK3SGxOwqUA7I3P6te4JAi41EXr1pFsyF-2FcDa2X0MbCMWVcr01cVxurtBp3x4khDU-2Fq2rZZvzjZSzYbN3dN8w-3D-3D\r\n\r\nYour DowntimeBot team","subject":null,"alert":false,"error":null}`

**Comment by RealRaven2000** [comment]
> > I know that's what I wrote on the comment for the Tb78 branch because the mime parser returns the raw multipart message. it can even be based encoded or encrypted in which v case the search will also not work. but it should work with the new method for Thunderbird 91.
> 
> Sorry, i haven't mentioned - it's for Thunderbird 91.0b1 (64-bit) with add-on version 56.
> 

Could you attach them email as "eml" file and your search expression for testing here? I could then import it into Thunderbird and check. Note that from Thunderbird 91 it should use the new function

`MimeParser.extractMimeMsg()`

This breaks up the mime parts into a subcomponents, while looking for "body" objects within.  At the moment the algorithm will test the very first "body" element it finds. The question is whether it should keep looking in the other "Body" parts if it can't find anything? In that case we could build an array and iterate that instead.

**Comment by rusak47** [comment]
[double_body_email.eml.tar.gz](https://github.com/RealRaven2000/FiltaQuilla/files/6899851/double_body_email.eml.tar.gz)
in this case, it's sufficient to seek for (bit\\.ly) - you can find it in text/html, but not in text/plain part.



> The question is whether it should keep looking in the other "Body" parts if it can't find anything? In that case we could build an array and iterate that instead.

I believe it should, and here you can see a good example why —

-  plain text part can differ from any other part of body,  
- first found part can be a shortened version of full body,
- and, maybe, something else…

**Comment by RealRaven2000** [comment]
So here is a test version:

[filtaquilla-3.2pre63.zip](https://github.com/RealRaven2000/FiltaQuilla/files/6901948/filtaquilla-3.2pre63.zip)

Instead of looking at just the first part I look at all of them. I think it should be restricted to certain content types though, but I have not enough knowledge to come up with a complete list. If the content type contains the string "html" I try to remove as many HTML tags (including any `<style>` section) as possible, but only with a Regular expression, so it's probably less than ideal. Should be enough to start you testing - your email will be matched in the second mime part in Tb92...

**Comment by rusak47** [comment]
Cool, thanks. First tests are successful, so i've merged your improvement into extracted callback version.

**Comment by RealRaven2000** [comment]
I have improved the body matching by only looking at MIME parts that are of type "text/anything" - so not looking at binaries (and hopefully attachments) anymore. so that should improve performance of HTML folders somewhat:

[filtaquilla-3.2pre86.zip](https://github.com/RealRaven2000/FiltaQuilla/files/6993327/filtaquilla-3.2pre86.zip)

**Comment by masscream** [comment]
Is there a way i could make it work, please, filtering outlook appointments (in TB)? I've tried making a Header RegEx filter (later also on body) for content-type "text/calendar", but none of my attempts worked. The only thing which actually "worked" was filtering the content-type header only, however it takes then any message, which is useless. I also tried adding the content-type into the mailnews.customDBHeaders  database, bur no success too. Thank you.

My filters:
```
content-type:/\b^text\b/
content-type:/\b^text\/calendar\b/
```
[example.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7502336/example.zip)

**Comment by masscream** [comment]
This is very probably something else, cause i can't make it work even on other headers (except the most common ones). I am sorry, but the documentation for this project is very incomplete or obsolete. Same as for the e-mail headers. Is it even an issue, shall I open a new one here? I am trying to make the Regex filter for the content-type header. I am adding it into mailnews.customDBHeaders in the format (my tries):

```
"content-type".
"content-type"
content-type
```
Still no luck, the header and its value keeps getting ignored. Please, I would be grateful for any advice. Or documentation, but I have been browsing for a while.

**Comment by RealRaven2000** [comment]
Implemented in 2.3 (released on 23/08/2021)

**Comment by masscream** [comment]
Still no luck with described content-type header, as in https://github.com/RealRaven2000/FiltaQuilla/issues/132

**Comment by plazer1** [comment]
> If the content type contains the string "html" I try to remove as many HTML tags (including any <style> section) as possible

This is incredibly unfortunate, and quite frankly, stupid. I want to filter messages **based on HTML tags**, which you remove before the regex matching. Also, most messages which have both `text/plain` and `text/html` bodies have the former exactly equal to the latter, but obviously without the HTML tags. So you're effectively trying to turn the `html` body into the `plain` body _which you already have_ by getting rid of all the useful information which can be used for filtering, and moreover, you are doing so in a very unreliable way ‒ not even using back-references.

Please consider getting rid of the HTML tag removal, or at least trying to match against the "raw `text/html`" body in case matching against the stripped body fails.

**Comment by RealRaven2000** [comment]
> > If the content type contains the string "html" I try to remove as many HTML tags (including any <style> section) as possible
> 
> This is incredibly unfortunate, and quite frankly, stupid. I want to filter messages **based on HTML tags**, which you remove before the regex matching. Also, most messages which have both `text/plain` and `text/html` bodies have the former exactly equal to the latter, but obviously without the HTML tags. 

See new issue #313 - enhancement request!
