### ISSUE TITLE
"From" "isn't in my address book" doesn't trigger on empty/invalid value

### ISSUE THREAD

**Issue by koswaiclu** [RealRaven2000/FiltaQuilla#116]
filtaquilla "From" "isn't in my address book" doesn't work/trigger on:
```
Return-Path: <>
From: Mail Delivery Subsystem <MAILER-DAEMON>
```

**Comment by RealRaven2000** [comment]
This is actually a feature of Thunderbird itself, so nothing that FiltaQuilla provides or can fix:
https://searchfox.org/comm-central/source/mail/locales/en-US/chrome/messenger/search-operators.properties#28

Better raise a new bug here:
https://bugzilla.mozilla.org/buglist.cgi?quicksearch=%22in+address+book%22+filter
