### ISSUE TITLE
The last update has a broken "Move later" broken in Thunderbird 78

### ISSUE THREAD

**Issue by raspopov** [RealRaven2000/FiltaQuilla#117]
After last update a week ago many filters just stop work.
My filters commonly contain the next actions:

- "Save Attachments to" or "Save message as file"
- "Move later"
- "Stop filter execution"

And the "Move later" not works again creating many duplicate files on disk.

**Comment by RealRaven2000** [comment]
> After last update a week ago many filters just stop work.
> My filters commonly contain the next actions:
> 
> * "Save Attachments to" or "Save message as file"
> * "Move later"
> * "Stop filter execution"
> 
> And the "Move later" not works again creating many duplicate files on disk.

Which version of Thunderbird are you running? Can you test whether the filters work correctly when you run them manually?

You could enable "Debug mode" on the About FQ tab:
![image](https://user-images.githubusercontent.com/6314674/130998349-b00355dd-18dc-42d4-abb1-8feff357df97.png)

then run JavaScript Error console  (Tb menu tools / developer tools / error console). See if any **fresh messages** appear when you run the filter. You can copy the log from the console using right-click / export visible messages to / clipboard :

![image](https://user-images.githubusercontent.com/6314674/130998556-aadfc5d6-93b7-4640-8f54-aca9b266dbeb.png)

**Comment by RealRaven2000** [comment]
Can you test the new prerelease version I left at issue #53?

**Comment by raspopov** [comment]
Version: 3.2.1pre3
Exception: ![](https://i.imgur.com/Tq3iB2k.jpeg)
_No other messages or exceptions, I runned the only one filter on the mail folder with the only one fitted message._

**Comment by RealRaven2000** [comment]
> Version: 3.2.1pre3
> Exception: ![](https://camo.githubusercontent.com/fb93afbddec67d681c73a30d00e59ae5b01ea9bb06762288f1a132db4d8623a7/68747470733a2f2f692e696d6775722e636f6d2f5471336942326b2e6a706567)
> _No other messages or exceptions, I runned the only one filter on the mail folder with the only one fitted message._

that's a very small stack - I need to add some debug info on the arguments to the copyMessage service to check. They renamed that one in Thunderbird 91, maybe it has slightly different parameter formats (not documented of course)..

**Comment by Ockenfuss** [comment]
Hello everyone,

I think I experience the same issue. Since August, the "Move later" seems to have stopped working. Are there any updates on this? Is this function still necessary when saving attachments?

Thank you! (also in general for the development of this awesome plugin!)

**Comment by RealRaven2000** [comment]
I tested it just now with Thunderbird 91.2 - and it moved a bunch of messages for me:

![image](https://user-images.githubusercontent.com/6314674/137497246-7eaf1ac2-30e6-4417-bfcc-9b8af8e3a7c5.png)

The only thing I saw _after_ it moved was this error message:

```
 Uncaught TypeError: this.messages.clear is not a function
    notify chrome://filtaquilla/content/filtaquilla.js:1944
```

however, this had no influence on the  working of the filter.

**Comment by Ockenfuss** [comment]
Ok, my mistake. I was still on the Thunderbird 78.x release channel. I switched to 91.2.0 now and it seems to be working with this version. Thank you very much for your answer!

**Comment by RealRaven2000** [comment]
> Ok, my mistake. I was still on the Thunderbird 78.x release channel. I switched to 91.2.0 now and it seems to be working with this version. Thank you very much for your answer!

Interesting - I would expect it to work in both versions - but maybe there is another change with the messages array. A lot of arrays were changed from the old `nsIMutableArray` type to a straight `Array` object in 78 already and I think the old types have been completely eradicated in 91. I would usually expect an exception to be thrown

**Comment by Ockenfuss** [comment]
Unfortunately, I do not know anything about the Thunderbird internals. Before I switched to 91.2.0, I checked that I was using the most recent 78.x version as of Oct. 16, 2021 (OS Windows 10), if this helps.
