### ISSUE TITLE
'javascript action with body' - javascript line used to work, now it doesn't

### ISSUE THREAD

**Issue by mirchie** [RealRaven2000/FiltaQuilla#118]
hi
i have been using the javascript action with body
msgHdrs.queryElementAt(0, Ci.nsIMsgDBHdr).folder.deleteMessages(msgHdrs, msgWindow, true, false, null, false);

to permanently delete emails (not send them to the trash - just dump them) that match the conditions, for years. it recently stopped working. i can't tell you when, exactly, since i just sort of noticed, earlier this week, that messages that should have been deleted were not.
i was on thunderbird 78 when it started, and i moved to TB 91, thinking that that might be the issue. it fails in both. i am on the version 3.2 of filtaquilla.
the error message in the filter log contains
"filterFailureAction" with error code=0x80570021

thanks!

**Comment by mirchie** [comment]
here is the output from the error console when i ran the filter on a specific email:

Uncaught TypeError: msgHdrs.queryElementAt is not a function
    <anonymous> chrome://filtaquilla/content/filtaquilla.js line 953 > eval:1
    applyAction chrome://filtaquilla/content/filtaquilla.js:953
    MsgApplyFiltersToSelection chrome://messenger/content/mailWindowOverlay.js:2763
    doCommand chrome://messenger/content/mail3PaneWindowCommands.js:1019
    doCommand chrome://messenger/content/mailTabs.js:842
    doCommand chrome://messenger/content/tabmail.js:581
    goDoCommand chrome://global/content/globalOverlay.js:123
    oncommand chrome://messenger/content/messenger.xhtml:1
    viewLog chrome://messenger/content/FilterListDialog.js:648
    oncommand chrome://messenger/content/FilterListDialog.xhtml:1
filtaquilla.js line 953 > eval:1:9
Prompter: internal dialogs not available in this context. Falling back to window prompt. Prompter.jsm:1084
Uncaught 
Exception { name: "NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS", message: "Component returned failure code: 0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS) [nsIMsgFilterService.applyFilters]", result: 2153185313, filename: "chrome://messenger/content/mailWindowOverlay.js", lineNumber: 2763, columnNumber: 0, data: null, stack: "MsgApplyFiltersToSelection@chrome://messenger/content/mailWindowOverlay.js:2763:26\ndoCommand@chrome://messenger/content/mail3PaneWindowCommands.js:1019:9\ndoCommand@chrome://messenger/content/mailTabs.js:842:23\ndoCommand@chrome://messenger/content/tabmail.js:581:27\ngoDoCommand@chrome://global/content/globalOverlay.js:123:18\noncommand@chrome://messenger/content/messenger.xhtml:1:12\nviewLog@chrome://messenger/content/FilterListDialog.js:648:10\noncommand@chrome://messenger/content/FilterListDialog.xhtml:1:1\n", location: XPCWrappedNative_NoHelper }
mailWindowOverlay.js:2763
An error occurred executing the cmd_applyFiltersToSelection command: [Exception... "Component returned failure code: 0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS) [nsIMsgFilterService.applyFilters]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://messenger/content/mailWindowOverlay.js :: MsgApplyFiltersToSelection :: line 2763"  data: no] globalOverlay.js:126

**Comment by RealRaven2000** [comment]
> hi
> i have been using the javascript action with body
> `msgHdrs.queryElementAt(0, Ci.nsIMsgDBHdr).folder.deleteMessages(msgHdrs, msgWindow, true, false, null, false);`
> 
> to permanently delete emails (not send them to the trash - just dump them) that match the conditions, for years. it recently stopped working. i can't tell you when, exactly, since i just sort of noticed, earlier this week, that messages that should have been deleted were not.
> i was on thunderbird 78 when it started, and i moved to TB 91, thinking that that might be the issue. it fails in both. i am on the version 3.2 of filtaquilla.

`nsIMutableArray` objects have been slowly deprecated out of all Mozilla products over the last 2 years.

I think in Tb78, msgHdrs is not an `nsIMutableArray` anymore, just a `nsIArray`:
https://searchfox.org/comm-esr78/source/mailnews/search/public/nsIMsgFilterCustomAction.idl#73

In Tb91 it's an `Array`:
https://searchfox.org/comm-central/source/mailnews/search/public/nsIMsgFilterCustomAction.idl#73

so I would try this:

`msgHdrs[0].folder.deleteMessages(msgHdrs, msgWindow, true, false, null, false);
`

Also make sure to check whether the `deleteMessages` parameters have not changed substantially:
https://searchfox.org/comm-central/source/mailnews/base/public/nsIMsgFolder.idl#465

**Comment by mirchie** [comment]
hi,
thanks for replying!
i tried your suggestion and it didn't work, but since this isn't an bug or issue with filtaquilla, there is no reason to keep it open. i will leave it up to you , the developer, whether you want to close it or not. who knows, someone may come along with a working solution for the change in js syntax.
i looked at your links, and tried some additional things that also didn't work. what is nice is that you gave me links to the actual syntax and parameters. i looked for a good while for this, before i posted. i am not familiar with js programming, but have some ancient coding background. i will tinker some more and see if i can hit on anything. in the meantime...i consder this closed, if you do.
thanks!!

**Comment by kgraefe** [comment]
It did work for me, though. Thank you!

https://github.com/kgraefe/thunderbird-autotag/commit/468a0dbdeca77e05143884039f53b543e2234e15

**Comment by mirchie** [comment]
> It did work for me, though. Thank you!
> 
> [kgraefe/thunderbird-autotag@468a0db](https://github.com/kgraefe/thunderbird-autotag/commit/468a0dbdeca77e05143884039f53b543e2234e15)

interesting! i'll try again.
so all you did was replace the original command with
msgHdrs[0].folder.deleteMessages(msgHdrs, msgWindow, true, false, null, false);
?

**Comment by mirchie** [comment]
nevermind! i pasted the suggested code, again, and it worked this time. i must have not copied the entire line, or something, when i first tried it.
closing, and thanks to both of you for your input!
