### ISSUE TITLE
Add ability to archive messages from filters

### ISSUE THREAD

**Issue by zabolyx** [RealRaven2000/FiltaQuilla#126]
A few years ago someone had modified the old version Mr. Kent was keeping to allow for archiving of emails. This simply invoked the built in archiving function of Thunderbird.

Would love to see that implemented again. Used that extensively with tags to organize my emails and move things to trash or archive as needed. I think I still have the edited XPI somewhere if that would be helpful.

**Comment by RealRaven2000** [comment]
Sure, can you attach the xpi (just rename it to filename.zip as github doesn't support sharing xpi in the comments) so I can have a look?

**Comment by zabolyx** [comment]
Here you go. Sadly all the info on who made the changes went away with the old Mesaquilla forums when they went off line.

[filtaquilla-1.2.1.kzA1-tb+sm.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7259778/filtaquilla-1.2.1.kzA1-tb%2Bsm.zip)

**Comment by RealRaven2000** [comment]
Here is a merged version, should be compatible with Tb78 and 91, can you test it?

[filtaquilla-3.3.1pre12.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7921030/filtaquilla-3.3.1pre12.zip)

**Comment by RealRaven2000** [comment]
Implemented in 3.4, released 18/03/2022
