### ISSUE TITLE
'Save message as file' action does not work properly with forwarded messages

### ISSUE THREAD

**Issue by Timaios28** [RealRaven2000/FiltaQuilla#131]
Hi.
I have tried the 'Save message as file' action and it works fine except when the received message that needs to be filtered is a forwarded one. Then it saves a simple 0 bytes 'fwd' file without extension. I've tried multiple thunderbird versions, from 78.14.0 portable to a 93.0.1 normal installation and I get the same result. The 'Save attachments to' action works fine with all kinds of messages. Note: The forwarded messages that were used for testing were from gmail.

Any thoughts?

**Comment by Timaios28** [comment]
So I did a little more digging and I found that if you forward a message, edit the subject and remove the fwd: , the 'Save message as file' works as intended

**Comment by RealRaven2000** [comment]
Interesting - some mismatch with the original email? We will see...

**Comment by Timaios28** [comment]
![example01](https://user-images.githubusercontent.com/93658703/140268655-5d8c9c9e-8d58-45f8-8c6c-3dac775d8a34.jpg)

I kept on digging a bit. Replying works. Replying multiple times to the same email works. Normal mail works. Only ' Fwd: ' in the subject causes problems, as seen in the picture. I noticed that when handling a 'reply', the action saves the email but removes the 'Re:' from the subject. On the other hand, when handling a 'forward', it tries to keep the 'Fwd:' and fails. I suspect that the colon ':' might be causing the problem. Maybe the algorithm that scans the subject to create the filename has problems dealing with the ':' ?

**Comment by Timaios28** [comment]
![example02](https://user-images.githubusercontent.com/93658703/140269874-cb5d6dd0-e77d-4c3c-b4cf-70ed6d796e88.jpg)
So, I finally did the obvious. I sent a normal email with a normal subject that I added a colon ':' in a random place (neither in the beginning nor the end). The action saved the email properly, but the filename didn't contain the part of the subject that was after the ':', as can be seen in the pic. It seems that the colon creates the problem but somehow it is more severe in 'Fwd:' .

**Comment by RealRaven2000** [comment]
>  So, I finally did the obvious. I sent a normal email with a normal subject that I added a colon ':' in a random place (neither in the beginning nor the end). The action saved the email properly, but the filename didn't contain the part of the subject that was after the ':', as can be seen in the pic. It seems that the colon creates the problem but somehow it is more severe in 'Fwd:' .

great stuff thanks for finding that - it will surely be helpful when I recreate the problem.

**Comment by Timaios28** [comment]
I think the problem is the fact that the windows filesystem does not accept the colon ':' in the filenames. I even used Thunderbird's built in 'Save As' ability and it saves the email using the subject as filename but removes the colon. If you try this in Linux, it will probably work as the filesystem accepts colons. I think the problem is that the addon tries to save a filename with a colon in it and that is a no no in windows. And for some reason it does it in Fwd: (it works fine in Re: - it removes the : there?). Just my two cents. Great addon, take care!

**Comment by Timaios28** [comment]
![linux example](https://user-images.githubusercontent.com/93658703/140659397-d3bae273-0908-49d2-9604-a7988aed1062.jpg)

Well, I copied the thunderbird profile from windows and I put it in Linux Mint. As expected, it works there. It almost certainly is the ':'. It needs to be cleared from all windows filenames generated using mail subjects because NTFS does not like it and I suppose other characters that cause the same problems with NTFS should be cleared from generated filenames as well, like / ? < > \ : * | "

Thanks for your time, take care!

**Comment by RealRaven2000** [comment]
There is a test version on #144 - I think this one can safely be regarded as duplicate.

**Comment by RealRaven2000** [comment]
Fixed in 3.3, officially released today (21/02/22)

**Comment by Timaios28** [comment]
I'll give it a try and let you know :)

**Comment by Timaios28** [comment]
![save email fwd rep ntfs weird chars problem fixed](https://user-images.githubusercontent.com/93658703/150634046-161a706b-a22e-4c05-8cd0-744be3656445.jpg)

It works. The normal email is ok, the forwarded email is OK, the only "problem" I can see is with the replied email, where it saves the filename but omits the "Re:" . Maybe it is deliberate? And even if it is not, it is not a big deal. Thank you for everything! Great work!
