### ISSUE TITLE
Can't find "Save attachment" in action of filters in Thunderbird 91

### ISSUE THREAD

**Issue by CherradMouna** [RealRaven2000/FiltaQuilla#133]
Hi I installed FiltaQuilla for Thunderbird 91 but I cannot find the action of Save attachments in filters 
Do you have idea ??

**Comment by RealRaven2000** [comment]
Enable it in FiltaQuilla settings:
![image](https://user-images.githubusercontent.com/6314674/142849123-d73f8007-651c-40f9-9baf-c2d71da3b8f3.png)

It's on the Filter Actions page:
![image](https://user-images.githubusercontent.com/6314674/142849170-7404cd5e-0370-4d50-b1bb-357159f027b8.png)

**Comment by CherradMouna** [comment]
Thanks for answering, I  have an other problem when applying the filtre of Detach Attachments To it duplicate the emails 
I found two or three copies of the same emails ??
