### ISSUE TITLE
Action of "Detach Attachments To" doesn't detach from message (only saves attachments)

### ISSUE THREAD

**Issue by logicg8** [RealRaven2000/FiltaQuilla#135]
Using IMAP with Gmail, a filter with action "Detach Attachments To" only saves the attachments for matched messages. The message remains with the attachment(s). Tested with 91.3.2 64-bit Thunderbird Mac OS.

**Comment by RealRaven2000** [comment]
try this new version - the previous one generated garbage file names.

[filtaquilla-3.6pre30.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9788229/filtaquilla-3.6pre30.zip)

download zip file and drag into Thunderbird Add-ons Manager to install. also restart Thunderbird (old filter actions cannot be removed, so only restarting will add the new version)

**Comment by RealRaven2000** [comment]
Included in release 3.6, published on 17/10.
