### ISSUE TITLE
question: memory not being released

### ISSUE THREAD

**Issue by richardh9935** [RealRaven2000/FiltaQuilla#138]
I'm not a programmer, but I have worked as a capacity manager, so I can read activity monitors.

Situation: I'm using FiltaQuilla to detach many files from my emails. To do this, I moved the biggest messages into a local folder. I then selected a few of them at a time. Initially, over 10, then finally, about five at a time. I configured the filter to only work on that sub-folder. This is on a mac mini, with the M1 chip and 16GB RAM, running macOS Monterey (12.0.1)

Observations: 
1. With messages under 2MB, Thunderbird and FiltaQuilla can cope quite well. 
2. However, Thunderbird quickly uses up memory, and then does not release it. (Attached images are of Activity Monitor, showing Thunderbird not releasing RAM until it is stopped by closing or force-quitting it.)
3. Once memory reaches 55GB, Thunderbird stops responding. Probably because the operating system refuses to offer it any more memory.
4. At that point, I must force-quit Thunderbird, and that means I've destroyed the open files.
5. Once Force-Quit, memory consumption returns to normal.
6. Then I try again, selecting fewer files.

Response: I've kept reducing the number of files until the process works. Memory consumption gradually increases, but I can keep working if I close Thunderbird before it gets to 55GB consumption.

I've attached screen images of Activity Monito
![Screen Shot 2021-11-29 at 15 14 02](https://user-images.githubusercontent.com/20249831/143809017-a00cd80b-5fec-45d5-acb4-221097f55339.png)
![Screen Shot 2021-11-29 at 14 24 08](https://user-images.githubusercontent.com/20249831/143809053-3b2da82a-0ca7-44aa-8b0e-b57565132663.png)
r.

**Comment by RealRaven2000** [comment]
That's a pretty serious loss of memory you have detected - are there errors in the error console when attachments are stored / detaching?

**Comment by RealRaven2000** [comment]
In the Developer Toolbox (Ctrl+Shift+I) there is also a memory tab, but I have never tried interpreting its results:

![image](https://user-images.githubusercontent.com/6314674/150150328-9e7e571e-7c83-4ab2-b80e-33d00dd86792.png)

Might be a good idea to ask on the Thunderbird Support matrix chat:
https://matrix.to/#/#thunderbird:mozilla.org

**Comment by richardh9935** [comment]
I have since then looked for other memory hogging problems associated with the new M1 chips, and there have been plenty. One software developer has specific instructions to M1 users. They are to download their recent compilers and interpreters again, and re-install (assemble) them. (eg Python) In that particular software case, this worked.

Apple has since updated macOS 12, and may have addressed the issue.

I interpret this to mean that the M1 microcode is somehow different from Intel microcode, but that can be overcome with re-assembling compilers and interpreters.

Thanks for your interest.
