### ISSUE TITLE
Print feature not working with other filters!

### ISSUE THREAD

**Issue by NastyNeightK** [RealRaven2000/FiltaQuilla#141]
With FiltaQuilla and NO OTHER addons, print is not working correctly unless it's the ONLY filter action. I used to have my filters Print, Mark as Read, Auto-Replay with Template, then Move to Folder. If I add in ANY of those other actions the print action prints a blank page. It WILL send a print job to the printer, but it doesn't load the document for printing, it just prints a blank page. When I removed all other filter actions it correctly prints the email. 

Basically when the print action is by itself, you will see the print status window say "Printing Document: (Title of Email Subject Here)"

If you try to use it with other filter actions it will say "Printing Document:                             "  and send a blank page to the printer.

This is the case with every version of Thunderbird I tried. It must have something to do with recent updates to FiltaQuilla. I'd love to see this working again because I have no other options for automating this.

EDIT: I figured out a workaround. I can't believe it took me this long to think of doing this, but if I just add a 2nd completely separate filter with the same requirements that only contains the rest of the actions I needed to do, it will work for my needs. However, it still is a legitimate issue that should be solved so that people can use print in conjunction with other filter actions inside of one filter. Hopefully this helps if someone is experiencing the same issue.

**Comment by RealRaven2000** [comment]
Please check #130 for a test version with some attempts at fixing printing.
