### ISSUE TITLE
Print Action no longer available in 91.5.1

### ISSUE THREAD

**Issue by archfiddler** [RealRaven2000/FiltaQuilla#149]
Why oh why do I let Thunderbird 'upgrade' and ruin my work flow?!! 'Missing Custom Action' instead of 'Print' in latest version. I downloaded your latest FiltaQuilla too so not sure if its Thunderbird or latest build.... Help!

**Comment by archfiddler** [comment]
Panic over, just downloaded latest latest version and 'Print' has returned.

**Comment by RealRaven2000** [comment]
You might also want to test drive the latest version which has some fixes related to printing (duplicates). I linked it on [issue 130 ](https://github.com/RealRaven2000/FiltaQuilla/issues/130#issuecomment-1020660522) first: 

[filtaquilla-3.3.1pre15.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7934519/filtaquilla-3.3.1pre15.zip)

to install this, please download the zip file and drag it into Thunderbird Add-ons Manager (without unpacking) - unfortunately I cannot upload as xpi format on github comments, but internally it's the same as a zip file and can be installed that way too.
