### ISSUE TITLE
Add support for PrintingTools NG Add-on

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/FiltaQuilla#152]
For the "print" action support a new option to use the print method of @cleidigh  in a filter action.

**Comment by RealRaven2000** [comment]
PrintingTools will implement a new message listener using runtime.onMessageExternal(..) which must accept a message Id which will be created by the sender of the message (the FiltaQuilla print process).

Resources for conversion:
https://webextension-api.thunderbird.net/en/latest/how-to/experiments.html#using-folder-and-message-types

this.extension.messageManager.get(messageId)

extension.messageManger.convert(realMessage)

Sending the message:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage

**Comment by RealRaven2000** [comment]
Pushed changes to ESR78 branch (= current master)
changeset:

https://github.com/RealRaven2000/FiltaQuilla/commit/a3730c6e69d61dc1feef951254d6aaf7fa3161e8

I had to add a Notify listener (through John Bieling's NotifyTools API) so I could call sendMessage from the background. 
Additional permissions needed: messagesRead and notifications

To enable output with PrintingTools NG enable the appropriate option on the "Filter Actions" tab:

![image](https://user-images.githubusercontent.com/6314674/153006389-b8595d3d-3053-46e0-a542-06bd8ab9496a.png)

**Comment by cleidigh** [comment]
@RealRaven2000 
I have the basics in, but I don't know the easiest way to get the xpi

@cleidigh

**Comment by RealRaven2000** [comment]
> @RealRaven2000 I have the basics in, but I don't know the easiest way to get the xpi
> 

@cleidigh If you don't want to pull [ESR78](https://github.com/RealRaven2000/FiltaQuilla/tree/ESR78) then just use the version below:

[filtaquilla-3.3.1pre21.zip](https://github.com/RealRaven2000/FiltaQuilla/files/8079247/filtaquilla-3.3.1pre21.zip)

Install from file should work:

![image](https://user-images.githubusercontent.com/6314674/154250804-e6e042ef-fa03-4230-87ba-711eb7003bbf.png)

**Comment by cleidigh** [comment]
@RealRaven2000 
I am setup and I enabled two actions in fq js and ptng
when i create a filter I see the added js action but only the js shows

am i missing configuration?
I did reboot after enabling the new actions

**Comment by RealRaven2000** [comment]
will have a look tomorrow!

**Comment by RealRaven2000** [comment]
@cleidigh can you commit your changes to your 2.0.7 branch?

Or attach your sources / xpi in a comment here... note that comments only accept zip format.

**Comment by cleidigh** [comment]
hey
I am online
2.0.7-b12 has the bk receiver 
it dumps the msg (no print yet)

i could not get the ptng action fq

time for a call?

**Comment by RealRaven2000** [comment]
ok, I mail you an invite now!

**Comment by cleidigh** [comment]
@RealRaven2000 

I just got the notify  exp working 
late so i have to patch in the rest tomorrow 
@cleidigh

**Comment by RealRaven2000** [comment]
> @RealRaven2000
> 
> I just got the notify exp working late so i have to patch in the rest tomorrow @cleidigh

Oh nice. do you know what it was? I hope my changes were useful to you too.

**Comment by cleidigh** [comment]
i just did the bare minimum example from JBs readme
i still have to get your bk changes in
but i think we have all the pieces!
C

**Comment by RealRaven2000** [comment]
Latest beta version supporting PrintToolsNG:
[filtaquilla-3.4pre50.zip](https://github.com/RealRaven2000/FiltaQuilla/files/8140189/filtaquilla-3.4pre50.zip)

I added a mechanism in the options that makes it clear that you need [x] Print enabled in order to activate PrintingToolsNG integration. If [ ] Print is not active the other option will be displayed grayed out (disabled):
![image](https://user-images.githubusercontent.com/6314674/155694752-2d5be5a0-578a-49d0-9ed2-a96266b9c393.png)

There is also a new debug switch, which can be activated in FQ settings on "_About FiltaQuilla / help_" by right-clicking the debug checkbox:

![image](https://user-images.githubusercontent.com/6314674/155694919-8d0c24b2-3679-4061-9185-e6ce22ae11f1.png)

Activating `extensions.filtaquilla.debug.PrintingToolsNG` will log a line for each email that is being sent to PrintingToolsNG:
printMessage ( 'Filtaquilla - print test' - 29/10/2021 12:01:25 )

To see these messages in error console, you have to enable "Show Content Messages".

Note: PTNG still needs to implement queueing for handling multiple messages / running automatically. It only works reliably when I run a filter manually on a single message.

**Comment by ASMarvin** [comment]
Hi,

I dont know if this thread is the right one, but I still got some issues with the print filters. The first message that gets printed always comes out 3-5 times. After that the other prints working as intended. Is this a known issue? How can I fix this? 

FiltaQuilla-Version: 3.3.1pre15
Thunderbird-Version: 91.6.2

**Comment by RealRaven2000** [comment]
> I don't know if this thread is the right one, but I still got some issues with the print filters. The first message that gets printed always comes out 3-5 times. After that the other prints working as intended. Is this a known issue? How can I fix this?
> 
> FiltaQuilla-Version: 3.3.1pre15 Thunderbird-Version: 91.6.2

Did you try 3.4pre50? It's linked above your question.

**Comment by ASMarvin** [comment]
> 
> Did you try 3.4pre50? It's linked above your question.

not yet. Will give it a try now!

**Comment by RealRaven2000** [comment]
Implemented in 3.4, released 18/03/2022
