### ISSUE TITLE
Automatic Printing after sending changes print.always_print_silent to true and doesn't change back

### ISSUE THREAD

**Issue by vonvoelksen** [RealRaven2000/FiltaQuilla#155]
Thunderbird 91.6.1
FiltaQuilla 3.3
Windows 10

What the title says:

I configured FQ so that it prints Emails with a specific word as topic. The mail gets print silently, but then everything ist printed silently until I change print.always_print_silent back to false. 
Don't know if it's working as intended or a bug.

PS: My first bugreport on Github, sorry if I forgot something.

**Comment by vonvoelksen** [comment]
So, I kind of "solved" it:

I tried the 3.40pre50 and the Printing Tools NG 2.0.7-b7. This didn't work. The email wasn't printed at all. So I deactivated Printing Tools and now it works just fine and does what I want.

**Comment by RealRaven2000** [comment]
> So, I kind of "solved" it:
> 
> I tried the 3.40pre50 and the Printing Tools NG 2.0.7-b7. This didn't work. The email wasn't printed at all. So I deactivated Printing Tools and now it works just fine and does what I want.

2.1 just came out on addons.thunderbird.net - it should work with that.

Also, don't forget to enable the support for it:

![image](https://user-images.githubusercontent.com/6314674/156831939-f0c1ee67-4cf2-4948-8f84-55907c4786ec.png)

The old method of printing did set
`print.always_print_silent = true`

which is really not great. But I am working with quite old kludgy code here, so it's good to have the NG support now and have the complexity of print configuration in a different place than Fq.

**Comment by vonvoelksen** [comment]
I haven't tested 2.1 yet because right now it works like I want. I'll try Printingtools on my private setup. 
Thank you for working on this addon. It is very useful and saves me a lot of time.
