### ISSUE TITLE
Make FiltaQuilla compatible with Thunderbird ESR 102 (or current beta)

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/FiltaQuilla#161]
I have started doing regression testing for the Thunderbird beta (100.0b2), here is the latest version:

[filtaquilla-3.5pre6.zip](https://github.com/RealRaven2000/FiltaQuilla/files/8506130/filtaquilla-3.5pre6.zip)

To install this version, download the zip file above, and drag it into Thunderbird Add-ons Manager (without extracting the contents)

**Comment by RealRaven2000** [comment]
relate issue #164 - currently a show stopper. Latest version (only fixes search terms)

[filtaquilla-3.5pre22.zip](https://github.com/RealRaven2000/FiltaQuilla/files/8853021/filtaquilla-3.5pre22.zip)

Related bug for Tb: https://bugzilla.mozilla.org/show_bug.cgi?id=1772376

**Comment by RealRaven2000** [comment]
New version for solving issue #164 

Fixes the missing search terms + actions!

[filtaquilla-3.5pre25.zip](https://github.com/RealRaven2000/FiltaQuilla/files/8894585/filtaquilla-3.5pre25.zip)

To install download zip file and drag into Thunderbird Add-ons Manager (don't unpack)

**Comment by 3LaHoonK** [comment]
Hello ,Thank you for supporting new versions of Firefox browser 

cc: @RealRaven2000 @cleidigh

**Comment by RealRaven2000** [comment]
> Hello ,Thank you for supporting new versions of Firefox browser

I guess you meant to say Mozilla based email client :) - this reminds me, still need to publish a new version on ATN. I would have liked to address the problem with playing sounds before, which would mean shipping wav files as Windows Thunderbird has trouble with mp3s (#167).

**Comment by RealRaven2000** [comment]
Completed in 3.5  - released on 13/07/2022
