### ISSUE TITLE
Edit fields for search terms / actions not displayed in Thunderbird 102.0b2 when dialog loads

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/FiltaQuilla#164]
This is obviously a regression caused by changes in Thunderbird Core. It is caused by code injected via 

```javascript
messenger.WindowListener.registerWindow("chrome://messenger/content/FilterEditor.xhtml", 
  "content/scripts/filtaquilla-filterEditor.js");
```

is not loaded in time so the appropriate functions don't get monkey-patched before the editor is filled with actions / search conditions.

The code works as expected when manually adding a filtaquilla specific search term or action, but the filter editor is incapable / fails to add these correctly from a saved filter, making once generated filters impossible to edit.

**Comment by RealRaven2000** [comment]
I had a brief call with @jobisoft, he suggested to find all custom elements and replace them with themselves after patching:

https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith

This should trigger the correct, patched versions for the UI. 

Question: will this also instanciate the correct event listeners?

**Comment by nkgm-bs** [comment]
Hi,
probably you're interested in the following discussion on topicbox:
https://thunderbird.topicbox.com/groups/addons/Ta7dc4ea69d14e2a4/onloadwindow-fires-too-late

Regards,
Günter

**Comment by RealRaven2000** [comment]
Screenshot of a test filter:

![image](https://user-images.githubusercontent.com/6314674/172147829-60f39745-cff8-4a2b-9ab5-f9f8dba53137.png)

Here is a filter you can load with quickFilters  "restore filters" button:
[patch test.zip](https://github.com/RealRaven2000/FiltaQuilla/files/8843877/patch.test.zip)

To load the patch file, install quickFilters:
[quickFilters-wx-5.5.2pre36.zip](https://github.com/RealRaven2000/FiltaQuilla/files/8843908/quickFilters-wx-5.5.2pre36.zip)

... then open Message Filters and use the Yellow "Restore filters.." button on the tololbar to import the filter:
![image](https://user-images.githubusercontent.com/6314674/172148798-7588289f-201d-466a-b379-27999f7de5e0.png)


To reproduce the problem in Thunderbird 102 beta1, use:
[filtaquilla-3.5pre6.zip](https://github.com/RealRaven2000/FiltaQuilla/files/8843886/filtaquilla-3.5pre6.zip)


Related bug on Thunderbird's bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1772376

To test the missing custom terms with FiltaQuilla they need to be enabled in FQ options:

- On the "_Actions_" tab, enable _Prepend to Subject, Remove Tag, Append to Subject, Launch File, Run Program, Detach Attachments To, Save Message as File, Move Later, Add Sender to ADdress List, Javascript action, Play Sound, Forward with SmartTemplate, Reply with SmartTemplate_
- On the "_Search Terms_" tab, enable _Subject Regex Match_ and _Bcc_.

**Comment by RealRaven2000** [comment]
> Hi, probably you're interested in the following discussion on topicbox: https://thunderbird.topicbox.com/groups/addons/Ta7dc4ea69d14e2a4/onloadwindow-fires-too-late


I had seen this, don't quite understand how you made it work. I came up with a wrokaround for the search terms (re-adding the elements and populating them from the search terms) - but sadly that wont work for the actions as they have no editable elements that can be re-added:

[filtaquilla-3.5pre22.zip](https://github.com/RealRaven2000/FiltaQuilla/files/8848310/filtaquilla-3.5pre22.zip)

```javascript
    let terms = document.getElementById("searchTermList");
    for (let i=0; i<terms.itemChildren.length; i++) {
      let el = terms.itemChildren[i];
      if (gFilter.searchTerms[i].attrib == -2) {
        if (gFilter.searchTerms[i].customId && gFilter.searchTerms[i].customId.startsWith("filtaquilla")) {
          // this is one of my own search terms...
          let val = el.querySelector("search-value");
          let filterVal;
          try {
            // evalute the nsIMsgSearchValue
            filterVal = gFilter.searchTerms[i].value.str;
          }
          catch(ex) {
            
          }
          if (filterVal && val && val.getAttribute("value") != filterVal) {
            console.log(`Fixing search term ${gFilter.searchTerms[i].customId} - re-adding value "${filterVal}" ...` );
            val.setAttribute("value", filterVal);
            el.replaceWith(el);
          }
        }
      }
      console.log(el);
    }

```

**Comment by nkgm-bs** [comment]
The workaround i'm using only works for the filterAction case. I can't say anything about the searchTerm case.

I found, that the function isValidForType() from the filterAction is always called before _getChildNode() is called. So i did a check in isValidForType if _getChildNode is already patched (which is the case up to TB100). If it is not already patched, i do it now. That seems to work, no need to deal with the DOM.

**Comment by RealRaven2000** [comment]
> The workaround i'm using only works for the filterAction case. I can't say anything about the searchTerm case.
> 
> I found, that the function isValidForType() from the filterAction is always called before _getChildNode() is called. So i did a check in isValidForType if _getChildNode is already patched (which is the case up to TB100). If it is not already patched, i do it now. That seems to work, no need to deal with the DOM.

Without code it still is hard to understand - do you have a diff you can point to? Do you add any custom edit fields in the action row? My understanding is that isValidForType may be called by the message filter dialog when it loads, but it does not help as long as none of my patch code has been called? what event / core function calls the function `isValidForType()` in your case?

**Comment by nkgm-bs** [comment]
isValidForType() is part of the filterAction object which you have to feed into MailServices.filters.addCustomAction(filterAction);
See your file filtaquilla.js e.g. line 186.

**Comment by RealRaven2000** [comment]
Here is a fixed version -  we managed to write a script loader module that loads the patch script earlier (on the `DOMContentLoaded` event):

[filtaquilla-3.5pre25.zip](https://github.com/RealRaven2000/FiltaQuilla/files/8894585/filtaquilla-3.5pre25.zip)

To install download zip file and drag into Thunderbird Add-ons Manager (don't unpack)

**Comment by RealRaven2000** [comment]
To do: 
- fix the dark lines on the folder icons - in dark mode these should be bright.
- maybe improve spacing (flex) on the lines, it looks irregular

![image](https://user-images.githubusercontent.com/6314674/173448898-634eda0e-134e-4b2b-9cec-eeadfa3c958a.png)

**Comment by RealRaven2000** [comment]
Latest fix for bad coloring in dark themes:

[filtaquilla-3.5pre29.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9049947/filtaquilla-3.5pre29.zip)

To install download zip file and drag into Thunderbird Add-ons Manager (don't unpack)

**Comment by RealRaven2000** [comment]
Fixed in 3.5  - released on 13/07/2022

**Comment by sebthom** [comment]
@RealRaven2000 I just encountered this issue in TB 102.8.0 even with filtaquilla 3.7. Is this a regression bug?

![image](https://user-images.githubusercontent.com/426959/226771288-250ceb3c-f2f4-4d4e-9930-1ef27abc9789.png)

**Comment by RealRaven2000** [comment]
I don't know can you load the previous version and see if it works there please?

**Comment by RealRaven2000** [comment]
Where do you get `From (RegEx)` from?? that does not seem to be part of standard FiltaQuilla. All other fields work for me (Thunderbird 102.9, should also work in the previous version):

![image](https://user-images.githubusercontent.com/6314674/226774849-3a61e6be-c110-4de1-beeb-16b947c94807.png)

**Comment by sebthom** [comment]
I had 3.6.1 installed before with the same issue. I haven't used the regex filters before. I just wanted to use them for the first time.

**Comment by RealRaven2000** [comment]
I still don't know how you get From(Regex) - are you sure these are provided by FiltaQuilla? These are the ones you can enabled from FiltaQuilla settings:

![image](https://user-images.githubusercontent.com/6314674/226775221-373e5652-5d17-4d7b-9d3b-06b513a600c7.png)

It looks like this: The labels "Header (Regex)" "From (Regex)" and "Subject (RegEx)" from _your screenshot_ are _not_ added by FiltaQuilla. Do you have another Add-on installed such as search tools NG or quick Search NG?

**Comment by sebthom** [comment]
I will check that and report back. thanks for the hint!

**Comment by sebthom** [comment]
@RealRaven2000 you were right, expression search NG was the culprit. Unfortunately you cannot see which addon contributed which filter in TB. So I ended up here. Thanks again for your responses.
