### ISSUE TITLE
Support printing the same email multiple times

### ISSUE THREAD

**Issue by git-seb** [RealRaven2000/FiltaQuilla#165]
Using Thunderbird 91.10.0 with FiltaQuilla 3.4. Unable to print emails twice eventhough I've added two print filter jobs with same details. This was possible before but not anymore.

Expected result:
When email comes in, gets printed twice.

**Comment by Radiomyme** [comment]
Same issue here. Like you, I've tried to set up multiple filters (up to 10), but still, one or two print maximum. I can see that the print was requested in the logs, but the dialog print window only shows once at maximum. 

Is there a workaround ?

**Comment by git-seb** [comment]
@Radiomyme Have not found a workaround yet. Hopefully this gets picked up soon. An outside workaround could be letting those emails sent to your inbox twice. But that is just too unlogic.

**Comment by Radiomyme** [comment]
I’ve tried to send the specific email to 4 different email accounts liked to the same thunderbird and a similar filter settings (if email object is like then print). Even with that only one or two emails are print while more that 10 are requested almost at the same time…

**Comment by RealRaven2000** [comment]
Can you try by installing the [PrintingToolsNG Add-on](https://addons.thunderbird.net/en-US/thunderbird/addon/printingtools-ng/?src=search) and the option to use it?

![image](https://user-images.githubusercontent.com/6314674/177774025-aabcf21a-1c97-4a99-abdf-8f3f6f1c5749.png)

**Comment by Radiomyme** [comment]
I’ve tried it, and the option is still active right now but nothing changed. I only get one print while I have 4 filters to get 4 prints… I don’t know if I have to activate something more with this add on.

**Comment by git-seb** [comment]
@RealRaven2000 Thanks for your reply. Actually using PrintingTools NG already for months together with your plugin. Printing multiple just stopped after some of the last major updates, not sure which one.

**Comment by git-seb** [comment]
Any news here or will there be looked at the issue?

**Comment by RealRaven2000** [comment]
didn't get a chance yet sorry. I would need to write some test routine for better print queueing because I don't want to waste too much paper :) It's a bit of a mystery that the print queue of the OS cannot catch all the print jobs that are sent it's way. I wonder whether @cleidigh has any insights?

**Comment by cleidigh** [comment]
All
Can I get info on the versions in use and an example setup?
Reading above it's not clear to me if all of the issue cases are involving PTNG or if this problem occurs with FiltaQuila alone.
@realraven and I need to understand to debug.
@cleidigh

**Comment by Radiomyme** [comment]
Hello, please find enclosed all the information regarding FiltaQuilla (3.5) and PrintingToolsNG (2.1.4) and Thunderbird (91.11.0). The filter is set when a new email is received and the object is containing a string. The goal is to have 4 print (the same filter is set 4 times).

![095EDCCA-EE81-4545-A07A-57A49CF95048](https://user-images.githubusercontent.com/7822725/182033764-97d00ad5-f445-4f74-8b25-17690b6884b3.png)
![E1A161B3-A717-431E-91DC-656F89CC4FD6](https://user-images.githubusercontent.com/7822725/182033765-15fc37ae-a02e-44c1-91b5-c5341646195b.png)
![F5902716-9C12-4340-8D78-0DC88AF05DE0](https://user-images.githubusercontent.com/7822725/182033766-37cb242f-4f15-4668-b171-ef6a00bf4a97.png)
![1491CB83-2D72-4E3E-851F-3D0631DACD12](https://user-images.githubusercontent.com/7822725/182033767-cca9ae4c-7aa0-40b1-b3dc-89836f17e2ee.png)
![8F58D5A5-5C1E-4663-BCC3-3E3AAAA8C145](https://user-images.githubusercontent.com/7822725/182033769-9d398fb6-4e7d-4b53-9812-be9a9a49c1d7.jpeg)
![09450F52-8FEB-4138-BC86-9DF23D9E8CC3](https://user-images.githubusercontent.com/7822725/182033770-6c1a4476-f0ae-4881-881b-e7d822a442d5.jpeg)
![F085BCD5-32BB-4A7B-997A-97533B29A038](https://user-images.githubusercontent.com/7822725/182033771-7da68aec-0fad-4ff8-bdf2-0990295cf499.png)

**Comment by cleidigh** [comment]
@Radiomyme 
@RealRaven2000 
I have reproduced this issue on my system.
From the debug you can see two incoming ext_print requests.
I have two filter rules.
The problem is that the second request has a null msg uri
@realraven  let me know how you want to proceed debugging...
@cleidigh 

<img width="960" alt="2022-07-31-16-54-02 " src="https://user-images.githubusercontent.com/25272315/182052485-89f9683f-f372-4b77-a551-44cf9baa16d5.png">

**Comment by RealRaven2000** [comment]
> @Radiomyme @RealRaven2000 I have reproduced this issue on my system. From the debug you can see two incoming ext_print requests. I have two filter rules. The problem is that the second request has a null msg uri @realraven let me know how you want to proceed debugging... @cleidigh

@cleidigh Can I configure PTNG so it generates files instead of printing to my printer in order to preserve paper? these are the global options available to me at the moment:

![image](https://user-images.githubusercontent.com/6314674/182129418-ef27bf86-6586-493a-be1e-25aad614ae94.png)

**Comment by cleidigh** [comment]
@RealRaven2000 
yes set the default printer to a pdf and just cancel the print. You will get and process the print requests but not print or save.
@cleidigh

**Comment by cleidigh** [comment]
@RealRaven2000 
Any luck?
@cleidigh

**Comment by RealRaven2000** [comment]
> @RealRaven2000 Any luck? @cleidigh

sorry I didn't have time to test that yet was quite busy with QuickFolders, lots of issues there ... I will get to this later this week!

**Comment by RealRaven2000** [comment]
> @RealRaven2000 yes set the default printer to a pdf and just cancel the print. You will get and process the print requests but not print or save. @cleidigh

how do I add "print to pdf" is this supported by the MS XPS Document Writer? Or do I need to install a special driver into Windows7? Here are the options I see:

![image](https://user-images.githubusercontent.com/6314674/182478189-e4267a96-4d8f-48a6-94c8-ddcf4d2a08b1.png)

**Comment by RealRaven2000** [comment]
Here is a test version  that should allow printing duplicates. but you have to set the about:config setting

extensions.filtaquilla.print.allowDuplicate = true

[filtaquilla-3.5.1pre2.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9245886/filtaquilla-3.5.1pre2.zip)

**Comment by cleidigh** [comment]
@RealRaven2000 
I guess you don't have any pdf drivers, the xps should do. Just cancel the print to file.
I'll try your beta.
@cleidigh

**Comment by cleidigh** [comment]
@RealRaven2000 
I tried beta with the duplicate setting true, but the second request comes in with messageHdr null

@cleidigh

**Comment by git-seb** [comment]
@RealRaven2000 Any news? I konw you're busy so thanks for at least looking into it when you can. I can confirm the latest beta didn't fix it for me either. Same as @cleidigh

**Comment by RealRaven2000** [comment]
New version below. I added a bunch of debug output and UI to allow duplicates:

![image](https://user-images.githubusercontent.com/6314674/184685347-f749e1de-413a-475b-8feb-61af64d2a377.png)

[filtaquilla-3.5.1pre13.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9338821/filtaquilla-3.5.1pre13.zip)

Restart Thunderbird  after installation to remove the old action.

**Comment by git-seb** [comment]
@RealRaven2000 I can confirm it works now. Thanks a bunch!

**Comment by Radiomyme** [comment]
@RealRaven2000 it works for me as well ! Thank you so much

**Comment by RealRaven2000** [comment]
Included in release 3.6, published on 17/10.

**Comment by cleidigh** [comment]
cool.
when I get time we can look at the printer/page options 
@cleidigh
