### ISSUE TITLE
"Play Sound" not playing sound on message filter trigger. V3.4

### ISSUE THREAD

**Issue by Marazar** [RealRaven2000/FiltaQuilla#167]
Have tested with included sounds and custom sounds. Other filter options behave as expected.

**Comment by RealRaven2000** [comment]
If you are in Windows: apparently Thunderbird couldn't play back mp3 sounds for years - see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1608773

Guess I have to ship the next version with wav files instead, which is a pity but I don't think there is any other workaround. Mozilla Core doesn't seem to be interested in this much.

**Comment by RealRaven2000** [comment]
I converted the bundled sounds from mp3 to ogg, that seems to work. Here is a test version:

[filtaquilla-3.5pre26.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9022236/filtaquilla-3.5pre26.zip)

Download archive and drop into Thunderbird Add-ons Manager to test this version.

The new sound files will be unpacked to the folder extensions\filtaquilla in the profile folder.

**Comment by RealRaven2000** [comment]
Since Thunderbird isn't capable of playing back mp3 I will also remove this file type from the file selector for FiltaQuilla sounds.

**Comment by RealRaven2000** [comment]
Implemented in 3.5 - released on 13/07/2022

 For licensing reasons, Thunderbird cannot play back mp3 files natively, please use the provided ogg files instead. You can convert your own sound files to ogg with the Software [freac (Free Audio Converter)](https://www.freac.org)

**Comment by shadoutmapes** [comment]
"filterFailureAction" with error code=0x80570021 on a mac client I've tried ogg, wav, and aiff (this is what it naturally filters to) in the log I get that error. Gonna tray a betabuild, but just FYI
