### ISSUE TITLE
change printer 

### ISSUE THREAD

**Issue by dougbitt** [RealRaven2000/FiltaQuilla#170]
How can I change the default printer settings, since the print dialog box is gone with FiltaQuilla on?

**Comment by RealRaven2000** [comment]
I suggest using [PrintingTools NG](https://addons.thunderbird.net/thunderbird/addon/printingtools-ng/) and enable the compatibility with that:

![image](https://user-images.githubusercontent.com/6314674/193458716-39f79126-4fea-4e49-a4a5-bb0ed3d21e90.png)

**Comment by RealRaven2000** [comment]
see also #245 for selecting a specific printer
