### ISSUE TITLE
Bug: After triggering, FiltaQuilla attempts to reply to any email with a SmartTemplate

### ISSUE THREAD

**Issue by KonstabelKen** [RealRaven2000/FiltaQuilla#173]
Context: I've been using SmartTemplate for years, great addon, no issues. Recently I've started using FiltaQuilla to trigger SmartTemplate.

Problem:
I've encountered a bug whereby ordinary email, not an email matching a FiltaQuilla condition, is now using the SmartTemplate used by the most recent FiltaQuilla trigger.

Circumstances:
This is true for both replies and new (blank) mail.
This is true across email accounts so long as the user accounts are added to same Thunderbird profile. i.e. even if the FiltaQuilla trigger is set for user@abc.com, a new mail or reply for user@xyz.com is opened using the last used FiltaQuilla chosen SmartTemplate.

I have a second machine that just has SmartTemplate, not FiltaQuilla, and it has not developed the problem.

If I restart Thunderbird, the problem goes away until FiltaQuilla is triggered, and thereafter the problem is introduced.

The number of times that a new mail or reply is opened with the SmartTemplate is variable, and _seems to be_ related to the number of mails triggered by FiltaQuilla. i.e. if FiltaQuilla has automatically triggered 1 reply with SmartTemplate, then the next 1 ordinary mail will also be with that same SmartTemplate. If FiltaQuilla has correctly triggered 3 times, then the next 3 ordinary mails will be via that SmartTemplate. The number of mails triggered changes, and I've yet to determine exactly why, and I'm continuing to observe, but this is my best current guess. After the as-yet-undetermined number of occurrences behaviour returns to normal.

The fact that this happens **on reply** as well as new mail is particularly problematic.
New mail doesn't have anybody in the To field whereas a reply does, and since it has an email address the template mail is sent immediately. I've sent a number of people some very strange (to them) replies because of this. It's pretty dangerous.

That means that while the bug exists, I need to remember to go offline before I click reply so that I can prevent replies erroneously sent via the FiltaQuilla + SmartTemplate combo if they are replied.

I realise that SmartTemplate has some settings allowing one to set up new mail, replies etc using a SmartTemplate. This bug is overriding those settings and replying with a different SmartTemplate, so it's not that.

Happy to send screen recordings / screenshots of various settings to the email address to help get to the bottom of this. Screen recordings would include personal info, so I wouldn't want to upload to YouTube and paste a link here, but I can send to the email address I use for pro support on SmartTemplate as I'm guessing it's the same for FiltaQuilla.

**Comment by RealRaven2000** [comment]
> I realise that SmartTemplate has some settings allowing one to set up new mail, replies etc using a SmartTemplate. This bug is overriding those settings and replying with a different SmartTemplate, so it's not that.
> 
> Happy to send screen recordings / screenshots of various settings to the email address to help get to the bottom of this. Screen recordings would include personal info, so I wouldn't want to upload to YouTube and paste a link here, but I can send to the email address I use for pro support on SmartTemplate as I'm guessing it's the same for FiltaQuilla.

Before you send any material, let me attempt to reproduce the problem here on a test profile. I assume this is on Thunderbird 102?

**Comment by RealRaven2000** [comment]
So I am able to reproduce the issue in Thunderbird 102, currently debugging to see how exactly this is happening .

**Comment by RealRaven2000** [comment]
This version should fix the problem - thanks for finding this! By the way it is a SmartTemplates bug - I opened [[issue 205](https://github.com/RealRaven2000/SmartTemplates/issues/205)] for dealing with it there 

[smartTemplate-fx-3.13pre60.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9234252/smartTemplate-fx-3.13pre60.zip)

To install, download the zip file and drag it into Thunderbird Add-ons manager (do not extract files)

**Comment by RealRaven2000** [comment]
@KonstabelKen can you please test the version and leave feedback over at https://github.com/RealRaven2000/SmartTemplates/issues/205#issuecomment-1201212353 ?

Thanks in Advance!

**Comment by KonstabelKen** [comment]
Sure thing, installed it yesterday. So far so good.

I'll use it for a couple days and then drop some feedback over at [https://github.com/RealRaven2000/SmartTemplates/issues/205#issuecomment-1201212353](https://github.com/RealRaven2000/SmartTemplates/issues/205#issuecomment-1201212353).
