### ISSUE TITLE
Thunderbird 102.2.2 doesn't save attachments when automatic downloading mails on startup. 

### ISSUE THREAD

**Issue by gitkomp** [RealRaven2000/FiltaQuilla#176]
I have filtres which saves attachments and change tags. When Thunderbird is running and e-mail comes, it works - saves file and changes tag, but when Thunderbird is not working, e-mail comes and then i run Thuderbird, it only changes TAG but not saves attachement.

**Comment by RealRaven2000** [comment]
I am just consolidating all issues that have to do with attachments (there are way too many and lots of duplicates) - is this one still an issue in Tb 115? please reopen where necessary.
