### ISSUE TITLE
'Save attachments to' and 'move email to folder' don't work together

### ISSUE THREAD

**Issue by LuigiBrito** [RealRaven2000/FiltaQuilla#179]
if this is done. thunderbird saves the attachments with 0 data inside. I suspect it interrupts itself and moves the folder asap breaking the save attachment process.

**Comment by RealRaven2000** [comment]
as workaround, try "move later" instead of move mail.

**Comment by LuigiBrito** [comment]
@RealRaven2000 I think that's the real solution

**Comment by skopalv** [comment]
I have similar problem with Archive message.
