### ISSUE TITLE
"Save Attachments To" alters attachment filename

### ISSUE THREAD

**Issue by wolffss** [RealRaven2000/FiltaQuilla#183]
The names of the attachments I have to work with have syntactically significant underscores in the filename.  When the attachment shows up in the destination folser, the underscores have all been deleted.  E.g.: the attachment named
     greeters_Flight_2022_10_20_12_15
shows up in the destination folder as
     greetersFlight202210201215
which breaks my application.  This issue is new; it was first noticed less than 48 hours ago.

**Comment by RealRaven2000** [comment]
does the attachment have no extension name? Tbh how the file name is stored in the email is still a bit of a mystery to me. I am seeing a lot of impossible names such as  "important: reply to this file!" which shouldn't really be possible as a file name. [The sanitizing function](https://github.com/RealRaven2000/FiltaQuilla/blob/ESR78/content/filtaquilla.js#L2426) I wrote for filenames have a limited set of allowed characters:
"-ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789" (Plus the . but only for the file extension.)
and replaces other characters with ones that look "close". 

Obviously I can add the underscore, what other legal file name characters are missing?

Here is a quick patch with that character added; it would be useful to get a more complete list of allowed characters:

[filtaquilla-3.6.1pre1.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9837339/filtaquilla-3.6.1pre1.zip)

To install, download zip file and drag it into Thunderbird Add-ons Manager (without extracting contents). 
PS: with custom actions you may have to restart Thunderbird after installation to make them work!

**Comment by wolffss** [comment]
Many thanks for the quick turnaround.  My app runs pretty much continuously until around 11:00 pm US/Eastern but then I have a 3-hour maintenance window and I'll install and try your patch.  Until then, because I know the filename syntax, I have a workaround in a dozen lines of code to put the underscores back in.  Ugly but effective.  On filenames: Consensus for UNIX-y systems seems to be the only forbidden characters are / and ASCII null; some characters such as space and | have to be escaped to avoid side effects.

**Comment by RealRaven2000** [comment]
I did a bit more work, and decided to allow the characters `(` `)` `_` `-` `+` `'` `!` `%` and also spaces; make for a lot more readable file names. I am also replacing the (illegal) character `&` with `+`.

you can now replace spaces within a file name with any single character of your choice (please enter `-` to restore previous behavior), with this new option:

![image](https://user-images.githubusercontent.com/6314674/197180453-c94db66e-e0e8-49f7-b1ef-deca2084cddb.png)

Examples for some file names that would only minimally be modified with the default (Space remains Space)

"That's a rather dank take.pdf" => unmodified
"Special Offer - Get 20% off today!.html" => unmodified
"What kind (of smoke & mirrors) is this.json" => "What kind (of smoke + mirrors) is this.json"

Note that trailing / preceding spaces will be trimmed away as they are illegal in most file systems.

New version:

[filtaquilla-3.6.1pre10.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9838361/filtaquilla-3.6.1pre10.zip)

To install, download zip file and drag it into Thunderbird Add-ons Manager (without extracting contents).
PS: with custom actions you may have to restart Thunderbird after installation to make them work!

**Comment by RealRaven2000** [comment]
The only thing with this chance that is debatable is the change from the (current default) of replacing spaces with `-` to the more natural feeling default of leaving spaces as spaces. Not sure how disruptive this change would be for existing users, but I definitely feel it is preferable to most (and especially new) users. Thoughts?

**Comment by wolffss** [comment]
I think most users would opt for the fewer changes the better, so if spaces are legal, leave 'em alone.

**Comment by mmits-chm** [comment]
I had the same problem that since the update to version 3.6.: the underscores in the file name are lost when detaching files.

Original file name in the attachment of the e-mail: example_name_xyz_3.pdf

After detaching the file: example_namexyz3.pdf

I just installed the quick patch (pre10 version). Now it's working fine again.
Thanks for the fast help!

**Comment by RealRaven2000** [comment]
I will close this for now, not sure if it needs to be reopened,
