### ISSUE TITLE
Attachments with underscores in their filenames are not saved correctly - or is this intended?

### ISSUE THREAD

**Issue by wfsicherheit** [RealRaven2000/FiltaQuilla#185]
Hi there,
I guess based on this issue (https://github.com/RealRaven2000/FiltaQuilla/issues/177) that got resolved, another issue arose:
The problem now is that filenames of attachments with "illegal characters" get stripped entirely. Our PDF files have underscores in their filenames that have to be kept exactly as they are. Now, FiltaQuilla doesn't copy the exact filenames anymore. All the underscores get stripped away. Can you please fix that or do you have another idea how to workaround this? We'll definitely have to downgrade to 3.5 until this gets resolved. See if that fixes our issue, temporarily.

Thank you so much in advance!

**Comment by RealRaven2000** [comment]
See issue #183 

There is a new test version and explanation of which characters are preserved at:

https://github.com/RealRaven2000/FiltaQuilla/issues/183#issuecomment-1286811808

**Comment by wfsicherheit** [comment]
Awesome, thank you so much for clarifying!

**Comment by RealRaven2000** [comment]
> Awesome, thank you so much for clarifying!

cool - if there are any additional characters that we should white list, ,make sure to add them to #183 
there is a replacement routine for Diacritics / Umlauts already in place.
