### ISSUE TITLE
Filters have been appearing doubled in Tb since a little while..

### ISSUE THREAD

**Issue by xlovinglyx** [RealRaven2000/FiltaQuilla#188]
When i open Tools, Message filters, New, Match all of the following:

Filter types appear doubled, from those i selected in filtaquilla's options .. .

& it's the same in the "Actions" field.

**Comment by xlovinglyx** [comment]
Tb 102.4.1
FiltaQuilla v3..6.1

**Comment by RealRaven2000** [comment]
> When i open Tools, Message filters, New, Match all of the following:
> 
> Filter types appear doubled, from those i selected in filtaquilla's options .. .
> 
> & it's the same in the "Actions" field.

restart Thunderbird? At least with actions, there is no way of removing actions so this would be expected after updating FiltaQuilla.

**Comment by xlovinglyx** [comment]
restarting never helped.

**Comment by RealRaven2000** [comment]
> restarting never helped.

what other Add-ons are you running?

**Comment by xlovinglyx** [comment]
i've re-checked again after the latest update & the doubles finally disappeared.

it's fixed.

**Comment by RealRaven2000** [comment]
> i've re-checked again after the latest update & the doubles finally disappeared.
> 
> it's fixed.

Maybe it's something Thunderbird did (all major changes to editor from my side were done a few versions ago) - I will close it for now.
