### ISSUE TITLE
Body Regexp match - throwing errors

### ISSUE THREAD

**Issue by dmcichy** [RealRaven2000/FiltaQuilla#192]
I have a message filter using **Body Regexp match** with a RegEx of "/comes.*via.*profile/i"

The only action I am taking is to add a STAR to the message.  Nothing fancy.

The developer console logs error after error with essentially the same error text.  Does this feature work?

![image](https://user-images.githubusercontent.com/62240953/200629813-fc8238d2-9b57-4d82-a309-dba94afd47ab.png)

**Comment by RealRaven2000** [comment]
What version of Thunderbird and is it an IMAP account, and do you download full messages?

this is the (Thunderbird internal) code that fails:
```js
    var messageSize = folder.hasMsgOffline(aMsgHdr.messageKey)
      ? aMsgHdr.offlineMessageSize
      : aMsgHdr.messageSize;
    var data;
    try {
      data = NetUtil.readInputStreamToString(stream, messageSize);
    }
```

So I assume the message header returns a size of 0 for some reason at this point in time

**Comment by dmcichy** [comment]
Version 102.4.2.  Yes it is an IMAP account.  Yes I download full messages.

Is the **Body Regex match** feature **supposed** to work?  I don't see it in your documentation anymore and I can find a lot of old forum posts about there being some issues with accessing a message BODY...

![image](https://user-images.githubusercontent.com/62240953/200678606-7bc27777-9a09-4ec2-b014-a5b4552be153.png)

**Comment by RealRaven2000** [comment]
> Version 102.4.2. Yes it is an IMAP account. Yes I download full messages.

cool, just checking.

> Is the **Body Regex match** feature **supposed** to work? I don't see it in your documentation anymore and I can find a lot of old forum posts about there being some issues with accessing a message BODY...

yes it is, I just tested it here with a simply forwarded message. (Small size, 15.4KB) 

![image](https://user-images.githubusercontent.com/6314674/200813731-fd117b8c-aa9b-48f3-84ff-9c03502de699.png)

However, in  your case the message header seems to report back a size of zero. Does it also happen if you run the filter manually on the same message? Does it work after "repair folder"?

Let's add some error console messages to drill down. For a test, make sure to enable "Debug mode" in FQ Settings / _About FiltaQuilla/Help_ to get the additional messages in error console:
![image](https://user-images.githubusercontent.com/6314674/200818525-e12f3867-8bc5-4734-820e-b3886dfb1fab.png)

[filtaquilla-3.6.2pre4.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9970523/filtaquilla-3.6.2pre4.zip)

the console should then show some more info about offline status, message header and folder (the later should be clickable to drill down). To install the version above, as always download the zip file and drop into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
PS: to get a nice error log, please use the context menu in error console (right-click any line and select "Copy all Messages") - you can delete the contents before the test to make it more focused

![image](https://user-images.githubusercontent.com/6314674/200819069-13b0917d-e1ff-4405-b5c3-ab52df11165d.png)

Recommended configuration for error console:

![image](https://user-images.githubusercontent.com/6314674/200819337-762133a0-0138-41a1-a621-a2d0d1106b9b.png)

**Comment by dmcichy** [comment]
Thank you for all the great info.  I did exactly as you suggested.

However, after ticking the DEBUG checkbox in Filtaquilla, everything worked and I could not get the error to repeat.  Go figure.

**Comment by RealRaven2000** [comment]
Closing this one, but opening a fresh one #260
