### ISSUE TITLE
Saved attachments are 0 bytes because of inline attachments

### ISSUE THREAD

**Issue by Fandangles** [RealRaven2000/FiltaQuilla#202]
Since an attachment stored inline in ThunderBird isn't actually decoded until the user selects the message to which it is attached and thus the attachment symbol doesn't show up until you do so, the automatic saving of attachments in FiltaQuilla results in 0 byte files being saved.

Of course, if the sender attaches something NOT INLINE, the automatic saving works and generates valid sized files.

When I check the order of filters saved in ThunderBird, "Mark As Read Filter" might have solved this problem if it had not been run second in the order of filters run, the first of which was "Save attachment to..." and this of course is a ThunderBird issue which affects FiltaQuilla.

Is there any way to get FiltaQuilla to mark a message as read first rather than by ThunderBird  so the attachment is then decoded and ready to be saved so that it no longer generates 0 byte files by FiltaQuilla?

**Comment by RealRaven2000** [comment]
I didn't actually know about this concept of "inline attachments" - seems somewhat of a contradiction to me. How do you create them?

> Is there any way to get FiltaQuilla to mark a message as read first rather than by ThunderBird so the attachment is then decoded and ready to be saved so that it no longer generates 0 byte files by FiltaQuilla?

I am somewhat doubtful that it's just "marking the message as read" that download / converts the content. It might be a lot of code that's ran when the message is opened interactively, so this requires a lot of research...

**Comment by smartcooky99** [comment]
> How do you create them?

One way is on a mobile phone (see attached image)

If you you write an email and use the **paper clip icon** (red arrow) to attach a file, it will attach as normal, and the receiver will see the paper clip icon in the attachment column. Filtaquilla will save automatically to the designated folder

However, if you use the **share image icon** (blue arrow), the file is embedded in the body of the email, and Filtaquilla either ignores it or saves a file with the correct filename, but of 0 bytes in size. The receiver will **not** see a paper clip icon in the attachment column, but they can still right-click on the image and save it as per normal
 
![2022-12-18 21 35 38](https://user-images.githubusercontent.com/120907248/208289094-741e89fd-fc9c-46c2-99e7-862a865ca763.jpg)

**Comment by RealRaven2000** [comment]
> If you you write an email and use the **paper clip icon** (red arrow) to attach a file, it will attach as normal, and the receiver will see the paper clip icon in the attachment column. Filtaquilla will save automatically to the designated folder
> 
> However, if you use the **share image icon** (blue arrow), the file is embedded in the body of the email, and Filtaquilla either ignores it or saves a file with the correct filename, but of 0 bytes in size. The receiver will **not** see a paper clip icon in the attachment column, but they can still right-click on the image and save it as per normal

On what mobile phone and what application exactly? I tried it on my Galaxy A41 with the gmail app, but there is no such button. There is attachment and then the send icon (looking like a paper airplane). on the bottom (on top of the keyboard) I have 2 emojicon icons (a round and a square one), a GIF button, a microphone for voice messages and a settings icon.

Maybe your mail editor allows adding images inline (like many HTML editors), but then it's just an inline image not an attachment. Maybe you can send me an example Email at thunderbirddaily at gmail dot com.

**Comment by smartcooky99** [comment]
Sent you a couple of example texts from my phone

**Comment by RealRaven2000** [comment]
I got 2 emails, the first  one "Attached using paper clip" had  an attachemnt.

The second email "Using share button" - had an inline image, no attachments.

```
  <body dir="auto" text="#000000" bgcolor="#ffffff">
    <div dir="auto"><img name="storage_emulated_0_Download_FilmRescueInternational_jpg_1671389754403"
src="data:image/jpeg;filename=FilmRescueInternational.jpg;base64,/9j/4AAQSkZJRgABAgEAYABgAAD/4Q52RXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAUAAAAcgEyAAIAAAAUAAAAhodpAAQAAAABAAAAnAAAAMgAAABgAAAAAQAAAGAAAAABQWRvYmUgUGhvdG9zaG9wIDcuMAAyMDIyOjEyOjEwIDE3OjAwOjEwAAAAAAOgAQADAAAAAf//AACgAgAEAAAAAQAABVygAwAEAAAAAQAAAvwAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABFgEbAAUAAAABAAABHgEoAAMAAAABAAIAAAIBAAQAAA.......v5df//Z"
        id="HEV1671389754403" onmouseover="imageMousePointerUpdate(true)" onmouseout="imageMousePointerUpdate(false)"
        style="" class="" width="308" height="171"></div>
```

The image is displayed like a small thumbnail but presumably has the full file size of the original image, blowing up the message to 1 Megabyte, just like in the attached version. the Thunderbird filter engine will not see inline data as "attachments" because they are just part of the main HTML document.

**Comment by RealRaven2000** [comment]
Do you want me to do any more testing? Just to repeat there are only "attachments" or inline images, there is no "inline attachments".

**Comment by RealRaven2000** [comment]
Closing for now, not sure if it is really to do with attachments, please reopen if still necessary
