### ISSUE TITLE
FiltaQuilla for thunderbird 102.6.0 - add on not accessable to search emails 

### ISSUE THREAD

**Issue by sscolnick-IT** [RealRaven2000/FiltaQuilla#203]
Currently trying to use FiltaQuilla on thunderbird 102.6.0 on mac m1. After I download the extentions I have access to modify the filter settings settings but I am not able to access it on any sort of toolbar to run against selected emails.

**Comment by RealRaven2000** [comment]
they are not on a toolbar, but will be visible as additional options (search terms / actions) when you edit a filter. 

Tools / Message Filters / New...

![image](https://user-images.githubusercontent.com/6314674/207933992-3b9e2c0d-6dc7-48ba-a906-23b4b95bd2d1.png)

if you like toolbar buttons for the most important filter actions, try out the quickFilters Add-on!

**Comment by sscolnick-IT** [comment]
Hey thanks for the help, Next time ill look at the Docs a bit harder!

**Comment by RealRaven2000** [comment]
> Hey thanks for the help, Next time ill look at the Docs a bit harder!

no worries! at it's easier to answer a question than fixing a problem :)
