### ISSUE TITLE
Can't Save attachments to when filter type="48" (Filter after verification of junks)

### ISSUE THREAD

**Issue by salmonslaw** [RealRaven2000/FiltaQuilla#214]
I noticed that the option to "save attachments to" doesn't work when the type of the filter is 48. Problem is that Filter log doesn't work when filter type is 17 (Filter before verification of junks); see [https://support.mozilla.org/en-US/questions/1160705] ) . So it's disappointing I have to chose: using the option "Save attachments" or having the log working. Any idea to solve this ?

**Comment by RealRaven2000** [comment]
Sorry, no idea. Only Thunderbird knows why the emails attachment cannot be saved during filtering before Junk controls are ran, maybe somebody [over at Thunderbird Core](https://bugzilla.mozilla.org) would know?

**Comment by salmonslaw** [comment]
@RealRaven2000 Thank you very much for your answer. I made some tests since then and had been able to solve it this way: after changing all rules type for "48" and confirm log was updated, I tried to switch back to other types (like "17") and realized that the log is working ! I don't know why but looks like that manipulation solves the log issue. So using type 17 is not a problem anymore.
