### ISSUE TITLE
Save Attachments To want work in some cases

### ISSUE THREAD

**Issue by gitFrank** [RealRaven2000/FiltaQuilla#221]
When two emails arrive at the same time.
The attachment of one of these emails should be saved (the other is a PayPal confirmation email).
Unfortunately, this does not happen in maybe 10% of the cases. The attachments are always the same. XML files with order data from a shop.
The filter is executed before junk detection.
What could be the reason?

**Comment by RealRaven2000** [comment]
the filter has to be executed after junk processing. I believe attachments are not ready otherwise.
