### ISSUE TITLE
Header Regex not showing

### ISSUE THREAD

**Issue by brettz9** [RealRaven2000/FiltaQuilla#222]
Hi,

I've adapted the file at https://github.com/RealRaven2000/FiltaQuilla/issues/209#issuecomment-1414006727 to point to a minimum version of 112, but I do not see Header Regex Match anywhere in the filters:

<img width="603" alt="image" src="https://user-images.githubusercontent.com/20234/230369758-8dc2242a-6ff4-4834-a5ba-71224a5e467d.png">

Is this because the beta is outdated or do I need to do something else to enable it?

Thanks so much!

**Comment by RayCulp** [comment]
Is `Header Regex Match` (2) enabled on the `Search Terms` tab (1) in FiltaQuilla's preferences?

![image](https://github.com/RealRaven2000/FiltaQuilla/assets/7621330/32df63f3-8956-4e6a-bd57-d226cbcd4aab)

**Comment by brettz9** [comment]
I'm currently using Thunderbird Beta, so unless you have a version ready for 118, my profile won't work with an older version. But thank you, that probably is the issue, as I don't recall enabling that!
