### ISSUE TITLE
Make FiltaQuilla compatible with Thunderbird 115 (ESR 2023/24)

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/FiltaQuilla#223]
I have created a new [branch ESR115](https://github.com/RealRaven2000/FiltaQuilla/tree/ESR115) for all changes related to the next version of Thunderbird (UI SuperNova). 

For backporting issues relating to 102 I have created another new [branch ESR102](https://github.com/RealRaven2000/FiltaQuilla/tree/ESR102)

Please report all bugs related to beta 113 and later below.

**Comment by RealRaven2000** [comment]
Starting additional compatibility tests today

- fixed `ToneQuilla.jsm` component (playback of sounds) by adding a background page. tested wav, ogg and mp3 playback.
- fixed updating version display in top panel of options screen (remove old version Proxy code)

[filtaquilla-4.0pre10.zip](https://github.com/RealRaven2000/FiltaQuilla/files/11759539/filtaquilla-4.0pre10.zip)

to install in Thunderbird beta, download the zip file and drag into Add-ons Manager (do not extract contents).

**Comment by RealRaven2000** [comment]
- Fixed "save as file..." action by using `MailServices`

[filtaquilla-4.0pre11.zip](https://github.com/RealRaven2000/FiltaQuilla/files/11763287/filtaquilla-4.0pre11.zip)

to install in Thunderbird beta, download the zip file and drag into Add-ons Manager (do not extract contents).

**Comment by obillard** [comment]
Hello and thank you for your work!
I updated to TB 115 today from 112 and updated the add-on to version 4.0b2, and I cannot make the "tag of thread messages" filter work (worked on 112).

```
Uncaught TypeError: message.folder.msgDatabase.GetThreadContainingMsgHdr is not a function
    threadAnyTag_matches chrome://filtaquilla/content/filtaquilla.js:1819
    associateView resource:///modules/SearchSpec.jsm:107
    _applyViewChanges resource:///modules/DBViewWrapper.jsm:1511
    _enterFolder resource:///modules/DBViewWrapper.jsm:1239
    open resource:///modules/DBViewWrapper.jsm:839
    _onSelect chrome://messenger/content/about3Pane.js:2507
    handleEvent chrome://messenger/content/about3Pane.js:1589
    set selectedRow chrome://messenger/content/tree-listbox.js:481
    _onClick chrome://messenger/content/tree-listbox.js:106
    handleEvent chrome://messenger/content/tree-listbox.js:76
352 filtaquilla.js:1819:49
    threadAnyTag_matches chrome://filtaquilla/content/filtaquilla.js:1819
    associateView resource:///modules/SearchSpec.jsm:107
    _applyViewChanges resource:///modules/DBViewWrapper.jsm:1511
    _enterFolder resource:///modules/DBViewWrapper.jsm:1239
    open resource:///modules/DBViewWrapper.jsm:839
    _onSelect chrome://messenger/content/about3Pane.js:2507
    handleEvent chrome://messenger/content/about3Pane.js:1589
    set selectedRow chrome://messenger/content/tree-listbox.js:481
    _onClick chrome://messenger/content/tree-listbox.js:106
    handleEvent chrome://messenger/content/tree-listbox.js:76

```

**Comment by RealRaven2000** [comment]
Looks like Core renamed `GetThreadContainingMsgHdr` to `getThreadContainingMsgHdr `. Try the test version below:

[filtaquilla-4.0pre18.zip](https://github.com/RealRaven2000/FiltaQuilla/files/12739670/filtaquilla-4.0pre18.zip)

---

to install, download zip file and drag the file into Thunderbird Add-ons Manager without extracting contents. Added search methods my not be removed successfully by Thunderbird, so restarting Tb is recommended before testing the new version.

**Comment by DeniR** [comment]
Where I can find Filtaquilla button in v115 interface ?

**Comment by RealRaven2000** [comment]
> Where I can find Filtaquilla button in v115 interface ?

there is no button - it's integreated into the Thunderbird filter editor. And you can enable additional search terms and actions in ADd-ons Manager under FiltaQuilla settings.

**Comment by Arondexter** [comment]
I need to filter on all Thunderbird messages with a Message ID that ends with microsoftstore1.microsoft.com
Can FiltaQuilla do this?
Any suggestions?

**Comment by RealRaven2000** [comment]
> I need to filter on all Thunderbird messages with a Message ID that ends with microsoftstore1.microsoft.com Can FiltaQuilla do this? Any suggestions?

can you open a new issue please? This one is closed, and the question is OT. If you ask specifically for Thunderbird 115, add it to the content of the issue. thanks in advance.
