### ISSUE TITLE
Regex search in subject finds matches in body too

### ISSUE THREAD

**Issue by ggikthuo** [RealRaven2000/FiltaQuilla#228]
I'm filtering mails with
Betreff vergleichen (Regulärer Ausdruck)  "/gewinn/i"
In the attached mail, this text is only in body, but the mail is filtered by this regex.
Any hint, whats going wrong?
regards
Georg
[Beispiel-Betreff-Regex_sucht_in_Body.txt](https://github.com/RealRaven2000/FiltaQuilla/files/12117866/Beispiel-Betreff-Regex_sucht_in_Body.txt)

**Comment by RealRaven2000** [comment]
can you please export the filter? If you have quickFilters installed you can use the  Backup button (hold down CTRL while clicking, then it will only export the selected filter(s))

![image](https://github.com/RealRaven2000/FiltaQuilla/assets/6314674/2d7adc16-62a7-4bfe-9f31-ad9d05900f5d)

**Comment by ggikthuo** [comment]
Thanks for responding so fast, here's the filter exported as recommended.
[filter.json.txt](https://github.com/RealRaven2000/FiltaQuilla/files/12138678/filter.json.txt)

btw. "[CTRL]+Filter abspeichern" speichert bei mir alle Filter, nicht nur den Selektierten.

**Comment by RealRaven2000** [comment]
You have a few search terms that use "subject + body" - (the one that contained "gewinn" wasn't one of these) - can you be sure that those didn't trigger the filter?

I wasn't able to import your example email, can you export it in "eml" format please?

**Comment by ggikthuo** [comment]
I checked this with regexr.com and didn't find a match, hope I didn't miss something.
I append the eml as zip, 'cause github doesn't accept .eml. I have replaced my mail address for privacy reasons.
When I saved the eml file and opened it again with TB, it tooks quite a while to oben it (about 1 min). That's a bit curious, maybe there's something wrong with the mail itself.
[Mail.zip](https://github.com/RealRaven2000/FiltaQuilla/files/12143836/Mail.zip)

**Comment by RealRaven2000** [comment]
Thanks now I could import the email - I am testing in my Thunderbird 115 test profile. However I couldn't import the filter anymore, did you edit the json file in some way?

 by the way, are you sure you cannot export a single filter using CTRL, it worked here. I exported a single filter:
![image](https://github.com/RealRaven2000/FiltaQuilla/assets/6314674/87629fe3-c8d4-4353-a035-b667539e5c8d)


This exports a "list" of filters with a single filter element, the JSON looks like this:

![image](https://github.com/RealRaven2000/FiltaQuilla/assets/6314674/378c7283-5c08-4a9f-ab52-3364c2c70bcd)

**Comment by ggikthuo** [comment]
Sorry, I stripped my mail from the filter, and saved as txt. (Github doesn't accept .json)
Here's the right one zipped. And CTRL Backup worked fine!?!
[Filter.zip](https://github.com/RealRaven2000/FiltaQuilla/files/12145676/Filter.zip)

**Comment by RealRaven2000** [comment]
ok -= thanks for that - I was able to import the filter

however it did not match with the email that I imported (screenshots heavily redacted)

![image](https://github.com/RealRaven2000/FiltaQuilla/assets/6314674/ba72792a-49eb-4aba-b57a-b6f6f1680470)

(I slightly modified the filter to star instead of mark as junk, but left the search term as is)

![image](https://github.com/RealRaven2000/FiltaQuilla/assets/6314674/424a8a12-37a4-41a3-a654-34f490bd386f)

all subject / body regex terms returned non-matches (I ran it through the debugger in Thunderbird inspector) are you sure that this was the filter that create the false positive? Or did you take out the "gewinn" from the subject search terms?

**Comment by RealRaven2000** [comment]
One more thing comes to mind - I have a global flag for case insentive searches set here

![image](https://github.com/RealRaven2000/FiltaQuilla/assets/6314674/993c3e04-6f70-43bd-8e33-e412f0d78ca2)

could this have interfered with your /i settings on your search terms? 

- I am not sure whether /i in the term is something the regex search supports ...
- I did add the checkbox as a convenience for less experienced users. not sure whether this is well tested with explicit /i flags

**Comment by RealRaven2000** [comment]
Do you need me to test on a different platform? I tested with Thunderbird 115.0.1 and FiltaQuilla 4.0b2

**Comment by ggikthuo** [comment]
I'm using TB 102.13.0 and Filta Quilla 3.7.2
I'm sorry, I'm going on vacation tomorrow, but I'll check more deeply when I get back at the end of August.
I will split the filter and try to narrow down the expression. And I'll also check the "/i".
Thanks for your help so far.

**Comment by ggikthuo** [comment]
Hello again,
sorry for the long pause. I have tried to reproduce my problem ... and I can't do it anymore!?!
What has happened in the meantime? I moved my mailstore from the QNAP NAS to a local hard drive (because of the many problems TB had with the profile on the NAS) and I updated to version 115.3.1 (64-bit). 
So we can close this thread and thanks for the help.
