### ISSUE TITLE
Extension Incompatible with Thunderbird 68+

### ISSUE THREAD

**Issue by apaarfus** [RealRaven2000/FiltaQuilla#25]
It would appear this extension is no longer compatible with the latest build of Thunderbird, 68.3.0.  Note entirely sure what would suddenly cause it to be incompatible, though.

### Description:

After upgrading from TB 60 to 68, most of my extensions appear to have been broken/disabled during the update.  In this case, FiltaQuilla appears to no longer be compatible, according to both Thunderbird itself, and the AddOn repository.

I just went through some of the recent PRs/commits -- it would appear that you're aware of the issue(s); but I figure I'll leave this open for now.

### Client Setup Information

- Extension Version: 1.5
- Operating System: Windows 7 Professional x64
- Thunderbird Version: 68.3.0

**Comment by RealRaven2000** [comment]
please see [[issue 15]](https://github.com/RealRaven2000/FiltaQuilla/issues/15) where this is handled. Conversionwork is underway!

**Comment by RealRaven2000** [comment]
There is a test version on the latest comment at:
https://github.com/RealRaven2000/FiltaQuilla/issues/15
