### ISSUE TITLE
Network path using Save Attachments To

### ISSUE THREAD

**Issue by tokkium** [RealRaven2000/FiltaQuilla#256]
Network paths are altered after restarting Thunderbird and become unusable in my case. 
Save Attachments To: `\\NEELIX\office\Scan\XXX\Name1 Name2\DSL\Invoice `
lose the first slash by restarting the program: `\NEELIX\office\Scan\XXX\Name1 Name2\DSL\Invoice`

Is this possibly my fault - how?

Sorry, haven't seen issue [#79](https://github.com/RealRaven2000/FiltaQuilla/issues/79#issue-761240059) before.

**Comment by RealRaven2000** [comment]
it's hard to fix, because I have no influence over how Thunderbird stores filters :(

**Comment by tokkium** [comment]
Thank you, I have already realized.
In my case I was able to use a simple workaround, network drive instead of UNC path. :-)
`N:\office` instead of `\\NEELIX\office`
