### ISSUE TITLE
Problem with Cyrillic symbols in the Run program action.

### ISSUE THREAD

**Issue by OlehRA** [RealRaven2000/FiltaQuilla#261]
I found a good solution to my problem in topic[ #254](https://github.com/RealRaven2000/FiltaQuilla/issues/254). However, I encountered an issue.
I'm using Run program '`:\Windows\System32\msg.exe,USERNAME,@AUTHOR@,@SUBJECT@`
The `msg.exe` program displays a message where Cyrillic characters are not correctly shown. Instead of the text written in Cyrillic, a set of symbols is displayed. 
![2024_04_25_09_29_02_Clipboard](https://github.com/RealRaven2000/FiltaQuilla/assets/115365160/e0bced0e-acda-4e97-bea2-2c92fe43836d)

**Comment by RealRaven2000** [comment]
thanks, I will test that one separately. It might be helpful if you can forward the email (attach as `eml` format, don't forward it inline!) off list to me directly (or attach it here if there are no privacy concerns), rather than me "making up" something in cyrillic for testing which may not work the same way...

**Comment by OlehRA** [comment]
How can I send you an EML file directly? I've created a private project and added you to it. 🙄

**Comment by RealRaven2000** [comment]
Is there a contact me on  the support page:

https://quickfilters.quickfolders.org/filtaquilla.html

if not I think there is such s link in the help page on FiltaQuilla options
dialog. sorry I cannot condom it tog now as I am out of office and not
close to Thunderbird....

https://addons.thunderbird.net/en-US/thunderbird/addon/filtaquilla/

this may have a support mail link as well.
Axel

**Comment by RealRaven2000** [comment]
I tried it, I think the subject line is read correctly, see this:

![image](https://github.com/RealRaven2000/FiltaQuilla/assets/6314674/49fc681c-4cf6-474a-b5de-8387390b84d3)

so the array of parameters passed to the process looks ok:

![image](https://github.com/RealRaven2000/FiltaQuilla/assets/6314674/28c92000-0f8c-44c3-9d97-55f5ff30aed9)

but I think that msg.exe cannot read the format of the parameter and then just garbles it. Can you try and for 16bit unicode with this option:

![image](https://github.com/RealRaven2000/FiltaQuilla/assets/6314674/36e7ccb7-f27a-46e3-ac2d-442d62a3828c)

**Comment by OlehRA** [comment]
Thank you, it's works! UTF-16 fixed this.
Can you please remove my email adress in screenshot from your post? Thank you again!

**Comment by OlehRA** [comment]
> 
> 


Please, remove my email from this screenshot

**Comment by RealRaven2000** [comment]
> Please, remove my email from this screenshot

done. Should have redacted right away, sorry for the oversight.
