### ISSUE TITLE
Create / Link to Forum or Discussions

### ISSUE THREAD

**Issue by TonyGravagno** [RealRaven2000/FiltaQuilla#273]
What do you think about adding a Discussion section to these repo's so that we can discuss how to use the addons and how to offer contributions for improvement?

Axel - I have other community-related ideas for these addons and Thunderbird devs in general, in addition to a Discussion section or instead of that. But I'd prefer to discuss them out of tickets or even off-site before surfacing them here.

Thanks.

**Comment by RealRaven2000** [comment]
I would have took into if this is something that Github supports. At the moment i am on annual leave, but if you remind me after July 31st in case i didn't get around to it we will come up with a way to do this.

**Comment by TonyGravagno** [comment]
I understand. This is how it is setup for any repo.

<details>

<summary>Screenshots</summary>

![240724083548](https://github.com/user-attachments/assets/53374f8e-7941-4bec-b5de-bff72fcfdb7d)

<hr>

![240724083727](https://github.com/user-attachments/assets/baa31334-90e4-4eaf-9ad7-3c76be54eb16)

<hr>

![240724083835](https://github.com/user-attachments/assets/77d45978-6724-4511-8b6e-0e5604719417)

</details>

In general:

- A Discussions section is for questions and answers, ideas, comments, and your own announcements.
- A Wiki is a collaborative place for accepted facts, HowTo, tutorials, links, how things work, nuances about specific aspects of the product, recognized issues that tend to get multiple tickets, things that aren't going to be done, plans for the future...

Enjoy this season!

**Comment by RealRaven2000** [comment]
understood:

https://github.com/RealRaven2000/FiltaQuilla/discussions/278

let's move / refer some of your recent suggestions there that would be helpful indeed. We can then create actionable issue for those items we deem actually as "feasible and able to implement"
