### ISSUE TITLE
"Train as Junk" in action list twice

### ISSUE THREAD

**Issue by TonyGravagno** [RealRaven2000/FiltaQuilla#277]
I'm not sure if this is coming from FQ, but ...

![image](https://github.com/user-attachments/assets/aa3eddcd-39ba-4137-87de-554952b109ea)

**Comment by RealRaven2000** [comment]
I was about to dismiss this as "Probably another bug in Thunderbird. Restart Thunderbird to see that it is gone." but I think there may be something to this one. With custom actions I believe there is no way to remove the via the service so this can lead to duplicates (which can be cleared by restarting Thunderbird). But if it happens straight away after adding a new search term this looks more like a legitimate bug in FiltaQuilla. 

![image](https://github.com/user-attachments/assets/135450d3-0ca0-4629-9551-4f6f8f08fa0e)


Tagging this one as bug and assigning to myself, Thanks!!

**Comment by RealRaven2000** [comment]
This was an easy fix. the following line was actually duplicated:
```js
    filterService.addCustomAction(self.trainAsJunk);
```
[filtaquilla-4.2pre2.zip](https://github.com/user-attachments/files/16372523/filtaquilla-4.2pre2.zip)

----

to install, download zip file and drag into Add-ons Manager. don't extract contents or it won;t install.

**Comment by TonyGravagno** [comment]
Hey! Stop writing code and go be on holiday somewhere! 😄

**Comment by RealRaven2000** [comment]
yeah don't worry this one was too easy, just deleting a single line of code, I couldn't resist. I did it as part of my customer support slot which I do every morning. The perls of running a one man show. Keeping the costs low. :P

**Comment by RealRaven2000** [comment]
Fixed in 4.2 - Published 15/10/2024
