### ISSUE TITLE
Since last version 09 27 2024 action save message as file generates en empty file

### ISSUE THREAD

**Issue by ManuManu06** [RealRaven2000/FiltaQuilla#301]
Hi, since last version dated 09 27 2024, the action "save message as file" generates a file which is empty. THere is also a question box saying something like that: "operating the filter generated an error, do you want to go on?"

**Comment by RealRaven2000** [comment]
> Hi, since last version dated 09 27 2024, the action "save message as file" generates a file which is empty. THere is also a question box saying something like that: "operating the filter generated an error, do you want to go on?"

do you have a version number? Go to Add-ons >> FiltaQuilla Settings and it's on the top right:

![image](https://github.com/user-attachments/assets/76f1db3f-e537-4686-bb06-2a8d8768d354)

I don't really care about the date it was created but every version that goes public (even test builds) has a unique number like that!

If you can reliably reproduce the problem by running filter manually, can you make a debug log (capture error console output, CTRL+SHIFT+J to open it); You can enable debug mode in FQ on the About / Help tab on the bottom right:

![image](https://github.com/user-attachments/assets/64cb74a7-a7fe-499d-add5-53679acc880d)

by right-click, also enable
`extensions.filtaquilla.debug.mimeBody = true`

- before you test, reset all contents of the console (this screenshot also shows what you need to switch on)
![image](https://github.com/user-attachments/assets/fa5d1df4-959c-4a2b-a58e-0f2b2bb9b63c)

- Run the filter manually
- after it failed go into error console and  "copy all messages"
![image](https://github.com/user-attachments/assets/d5129fac-5fa7-4323-ac73-311e468e1262)

**Comment by SashaZt** [comment]
Hi, did I write the filter C:\Temp\Emails\%accountname%\%date%_%subject%.eml for saving emails to files correctly?

**Comment by RealRaven2000** [comment]
> Hi, did I write the filter C:\Temp\Emails%accountname%%date%_%subject%.eml for saving emails to files correctly?

not sure, did you share more information? you can export it with quickFilters Pro if you like.

**Comment by SashaZt** [comment]
> > Hi, did I write the filter C:\Temp\Emails%accountname%%date%_%subject%.eml for saving emails to files correctly?
> 
> not sure, did you share more information? you can export it with quickFilters Pro if you like.

i.e. saving letters to a file is only possible with the PRO version?
I just need to save emails to files

**Comment by ManuManu06** [comment]
Hi Axel. THanks for your interest in this matter.

Version number is    4.1

Console content : (I add 2 screenshots)

Could not create file with name:test pour filta quimlla.eml filtaquilla.js:2452:15
Uncaught TypeError: service.SaveMessageToDisk is not a function
    _saveAs chrome://filtaquilla/content/filtaquilla.js:2449
    applyAction chrome://filtaquilla/content/filtaquilla.js:1199
filtaquilla.js:2449:15
sizeToContent() est obsolète et sera supprimé prochainement. commonDialog.js:132:10

![Capture](https://github.com/user-attachments/assets/92b58e20-ccae-4366-b31d-1835ad59dd7d)


Hope this helps you. Regards

**Comment by RealRaven2000** [comment]
> > not sure, did you share more information? you can export it with quickFilters Pro if you like.
> 
> i.e. saving letters to a file is only possible with the PRO version? I just need to save emails to files

Nope there is no Pro version. FiltaQuilla is still "free as in beer" and all the functionality comes as is. But obivously I am not going to spend as much time on fixing stuff here (and it's hell'a hard to understand, super low level, unsupported by Thunderbird and often unreliable code because I am not giving the heavy lifting to an API - my hope it that some of it can be moved to mail extension APIs in the future). It's tricky because we would need to re-code at least the actions as async to use the API functions. And you cannot save anything to file with an API, because APIs do not get file system access!

**Comment by RealRaven2000** [comment]
> Could not create file with name:test pour filta quimlla.eml filtaquilla.js:2452:15
> Uncaught TypeError: service.SaveMessageToDisk is not a function
> _saveAs chrome://filtaquilla/content/filtaquilla.js:2449
> applyAction chrome://filtaquilla/content/filtaquilla.js:1199
> filtaquilla.js:2449:15
> sizeToContent() est obsolète et sera supprimé prochainement. commonDialog.js:132:10

can you check issue #270 ? I think this one is a duplicate. and there may be a version there for you to test.

**Comment by SashaZt** [comment]
> Hi Axel. THanks for your interest in this matter.
> 
> Version number is 4.1
> 
> Console content : (I add 2 screenshots)
> 
> Could not create file with name:test pour filta quimlla.eml filtaquilla.js:2452:15 Uncaught TypeError: service.SaveMessageToDisk is not a function _saveAs chrome://filtaquilla/content/filtaquilla.js:2449 applyAction chrome://filtaquilla/content/filtaquilla.js:1199 filtaquilla.js:2449:15 sizeToContent() est obsolète et sera supprimé prochainement. commonDialog.js:132:10
> 
> ![Capture](https://private-user-images.githubusercontent.com/183061614/371488635-92b58e20-ccae-4366-b31d-1835ad59dd7d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTE1NjgsIm5iZiI6MTcyNzQ1MTI2OCwicGF0aCI6Ii8xODMwNjE2MTQvMzcxNDg4NjM1LTkyYjU4ZTIwLWNjYWUtNDM2Ni1iMzFkLTE4MzVhZDU5ZGQ3ZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxNTM0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmNmM2E0N2UxODZlYjU4Zjg1MmJlNWZiNGZhOTMxOWRkYTFlYzk5NjUwZTY4YzNlNGJjNTM0YTA5ZmRjOTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hM6j06xITyfQPpoB2lYBEh79qQXbiXFLy0kXKmWytPc)
> 
> Hope this helps you. Regards

where to apply this?

**Comment by ManuManu06** [comment]
> > Could not create file with name:test pour filta quimlla.eml filtaquilla.js:2452:15
> > Uncaught TypeError: service.SaveMessageToDisk is not a function
> > _saveAs chrome://filtaquilla/content/filtaquilla.js:2449
> > applyAction chrome://filtaquilla/content/filtaquilla.js:1199
> > filtaquilla.js:2449:15
> > sizeToContent() est obsolète et sera supprimé prochainement. commonDialog.js:132:10
> 
> can you check issue #270 ? I think this one is a duplicate. and there may be a version there for you to test.

THank you Axel. With the version in #270 , it works OK now. THank you for that. Regards.

**Comment by ManuManu06** [comment]
THank you Axel. With the version in https://github.com/RealRaven2000/FiltaQuilla/issues/270 , it works OK now. Very useful extension for me. THank you for that. Regards.

**Comment by SashaZt** [comment]
[09/30/2024, 03:22:41 PM] Failed to apply filter: "filterActionFailed" with error code=0x80570021 when trying to: Filter "SavingMails" applied to message from "Manyvids <sales@manyvids.com>" (subject "Vid SOLD!", date "09/29/2024, 02:47:18 PM"), Save message as file
my template C:\Temp\Emails\%date%_%subject%.eml
I need it as html format
**please help**

**Comment by RealRaven2000** [comment]
> [09/30/2024, 03:22:41 PM] Failed to apply filter: "filterActionFailed" with error code=0x80570021 when trying to: Filter "SavingMails" applied to message from "Manyvids [sales@manyvids.com](mailto:sales@manyvids.com)" (subject "Vid SOLD!", date "09/29/2024, 02:47:18 PM"), Save message as file my template C:\Temp\Emails%date%_%subject%.eml I need it as html format **please help**

What is error code 0x80570021? have you tried [filtaquilla-4.2pre4.zip](https://github.com/user-attachments/files/16322132/filtaquilla-4.2pre4.zip) over at https://github.com/RealRaven2000/FiltaQuilla/issues/270#issuecomment-2241273129 ?

is there an error log we could read?

**Comment by EKCJ** [comment]
I was also having this issue, which turned out to be due to a filepath issue - I am saving files to a network share at `\\SERVER\directory`, and somewhere inbetween me creating the filter and it running, one of the leading \s was dropped resulting in the failure.

In case it's useful, the console error I received was:
`Uncaught NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]
    applyAction chrome://filtaquilla/content/filtaquilla.js:1195
[filtaquilla.js:1195](chrome://filtaquilla/content/filtaquilla.js)
    applyAction chrome://filtaquilla/content/filtaquilla.js:1195`

And the filter log message matched @SashaZt 's error:
`[12/10/2024, 17:07:09] Filter Action Failed: "filterActionFailed" with error code=0x80520001 while attempting: Applied filter "Paperless message save" to message from *** at 12/10/2024, 15:37:15 Save Message as File `

Using Thunderbird 128.3.1esr 64-bit, and FiltaQuilla 4.2pre4

**Comment by RealRaven2000** [comment]
> I was also having this issue, which turned out to be due to a filepath issue - I am saving files to a network share at `\\SERVER\directory`, and somewhere inbetween me creating the filter and it running, one of the leading \s was dropped resulting in the failure.
> 
> In case it's useful, the console error I received was: `Uncaught NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath] applyAction chrome://filtaquilla/content/filtaquilla.js:1195 [filtaquilla.js:1195](chrome://filtaquilla/content/filtaquilla.js) applyAction chrome://filtaquilla/content/filtaquilla.js:1195`

it's a limitation of the field that stores the text for the path, the best workaround is to create a mapped network drive and start the path with that letter. Not sure whether that is possible in Linux / Mac.
