### ISSUE TITLE
FiltaQuilla 4.3.1 filters not working on Thunderbird 128.5.2esr

### ISSUE THREAD

**Issue by knoxg** [RealRaven2000/FiltaQuilla#322]
Thunderbird version: 128.5.2esr (64-bit)
FiltaQuilla version: 4.3.1

This seems like a regression, creating an issue in case anyone else encounters it.

This morning my filters were no longer working. When I tried to view those filters under Tools -> Message Filters, the first dropdown box was showing "Missing Custom Term" ( similar to the screenshot in issue #42 ).

![image](https://github.com/user-attachments/assets/1b9eb079-ac91-4a2e-86f0-c39fa53f6b57)

Unlike the other issue though, the addon options were no longer available. 
For what it's worth, the addon icon is also missing on the Extensions page:

![image](https://github.com/user-attachments/assets/2a103d4c-ecf0-43fb-98d7-3b96bab6a175)

On the release notes page at https://quickfilters.quickfolders.org/fq-versions.html I noticed FiltaQuilla 4.2 added support for Thunderbird  128, so I downgraded to the earlier 4.1 version by installing the XPI from https://addons.thunderbird.net/en-GB/thunderbird/addon/filtaquilla/versions/?page=1#version-4.1 and disabling automatic updates.

After reverting back, the addon icon is back, filter options are back, and filters are working again.

![image](https://github.com/user-attachments/assets/586fe080-a930-4f2b-99ff-9bd25f79f930)

Thunderbird 128 ESR is still the latest 'Extended Support Release' so think most users will be sticking to this version for a while.

**Comment by RealRaven2000** [comment]
It looks like it didn't complete the install for you!

I tested 4.3.1 both in 134.0b4:

![image](https://github.com/user-attachments/assets/008b7751-ed8f-4a22-8831-ded297f4828a)

and in 128.5.1:

![image](https://github.com/user-attachments/assets/c881df08-2a4f-4743-bf2a-7d72fc5de1f5)

I highly recommend **removing 4.1**, then installing 4.3.1 and then **restarting Thunderbird** before you test again. Should it still be blocked then, please make a debug log; details are described here:

https://quickfilters.quickfolders.org/bugs.html

The only difference would be to enable debug log not in quickFilters settings but in FiltaQuilla Settings on the about FQ / Help page of the dialog:

![image](https://github.com/user-attachments/assets/7bafa582-ee4e-42a9-8fd6-1d250221ea63)

**Comment by knoxg** [comment]
Thanks, uninstalling the add-on and reinstalling worked great :) 

Not sure how it got into this state but looks like the same thing has happened to another unrelated add-on so will try reinstalling that as well. 

Thanks for the quick response.
