### ISSUE TITLE
filtaquilla becomes unavailable version 2.0 hc

### ISSUE THREAD

**Issue by patugo** [RealRaven2000/FiltaQuilla#36]
Hello,

I used to have the previous version.  I've selected "delete" in the addon menu. Restarted thunderbird.
-select --tools-addons and search for filtaquilla.
-select to install it.
-restart thundebird.
-seems to work with old filters, that apparently were left behind by old version.
-version is 2.0.
-restart thunderbird a couple of times, seems fine. Until an unkown trigger that makes this addon go to version 2.0 HC and from that point on it no longer works.
When trying to create a new filter with that weird version, I see that all the regex filters, folders etc that ARE selected in the addon "search terms" are not displayed or available.

o.s. = kde neon
thunderbird version = 68.2.2

**Comment by RealRaven2000** [comment]
Ok, this means there was a crash in the firstRun code (that's the update checker) It actually needs the addon manager to tell it (asynchronously) the real version of FiltaQuilla so I can check whether it has the latest version (2.0) installed.

You need to check Javascript error console (Ctrl+Shift+J) straight after starting Thunderbird and if you can copy the complete error log (as text). Right-click, Select all, then Right-click Copy message will give you the complete log. 

For extra error detail it would be helpful if you could activate debug mode on Tools / addon Op tions / FiltaQuilla  on the About / Help tab and check the debug checkbox. You can also add more detail to the startup code by right-clicking the debug checkbox and also activate the option

` extensions.filtaquilla.debug.firstrun = true`

![image](https://user-images.githubusercontent.com/6314674/71025806-be51c280-20ff-11ea-8365-8fe77d02cc1a.png)

**Comment by RealRaven2000** [comment]
one more thing, do a separate log (reset before you open filter editor) while opening the filter editor. It's the editor that fails, and it runs the firstRun code again, so maybe it is crashing there.

**Comment by RealRaven2000** [comment]
3rd question - can you check about:config and see what it says in `extensions.filtaquilla.version` ?
I assume `extensions.filtaquilla.firstRun = false`.

**Comment by patugo** [comment]
ok so here's what I've got:
error comsole:
---
---
Error: Cannot find loader for bootstrap 2 XPIProvider.jsm:1877:15
Error while loading 'jar:file:///usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:513
    readJSON resource://gre/modules/Extension.jsm:513
    onStopRequest resource://gre/modules/NetUtil.jsm:128
1576648505544	addons.xpi	WARN	Exception running bootstrap method startup on messagingmenu@mozilla.com: Error: Error while loading 'jar:file:///usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi!/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:513:20) JS Stack trace: readJSON/</<@Extension.jsm:513:20
onStopRequest@NetUtil.jsm:128:9
WebExtensions: Loading packed extension from /home/sp/.thunderbird/igu4gys8.default/extensions/filtaquilla@mesquilla.com.xpi ext-legacy.js:157
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:8
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:9
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:10
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:11
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:12
WebExtensions: Loading add-on preferences from  /home/sp/.thunderbird/igu4gys8.default/extensions/filtaquilla@mesquilla.com.xpi ext-legacy.js:190
WebExtensions: Firing profile-after-change listeners for filtaquilla@mesquilla.com ext-legacy.js:194
1576648506099	addons.xpi	WARN	Can't get modified time of /usr/lib/thunderbird/features/wetransfer@extensions.thunderbird.net
VersionProxy
window is not defined filtaquilla-util.js:430
---
---

starting toe filter editor:
---
---
FiltaQuilla 1:0:40.614  [63265 ms]   
fq_FilterEditor.js - start...
FiltaQuilla 1:0:40.615  [1 ms]   
fq_FilterEditor.js - Finished.
---
---

the extensions.filtaquilla.version is 2.0
the extensions.filtaquilla.firstrun is false.


I've notice in the errors about  "ext-legacy" , maybe that's an indication.

**Comment by RealRaven2000** [comment]
thanks for that - I am wondering about messagingmenu@mozilla.com.xpi - whether this is really a build in thing or some other external extension; I need to do some research on this,,,

**Comment by RealRaven2000** [comment]
> thanks for that - I am wondering about [messagingmenu@mozilla.com.xpi](mailto:messagingmenu@mozilla.com.xpi) - whether this is really a build in thing or some other external extension; I need to do some research on this...

So it looks this may be something specific to the Debian packaged version, found it listed here:
https://packages.ubuntu.com/xenial-updates/amd64/thunderbird/filelist

Would it be possible to install the official Linux version from here instead?
https://www.thunderbird.net/en-US/thunderbird/all/#E
