### ISSUE TITLE
Restore feature - play a sound

### ISSUE THREAD

**Issue by sometimegithubuser** [RealRaven2000/FiltaQuilla#39]
Thank you for taking over FiltaQuilla, my wife and I missed it features. 

There is one action we'd like to see restored, "Play a Sound". We have switched to Mailbox Alert, but there are times when we want different sounds for the same mailbox based on e.g. who sent the email, or the subject, etc. We used to do that with FiltaQuilla in TB < 60, and in TB > 60 with the add-on compatibility disabled. But when we moved TB 68's profile to a new Windows 10 PC, TB refused to load the old FiltaQuilla, so we lost the ability for a filter to play a sound of our choosing. 

Thank you - Justus

**Comment by RealRaven2000** [comment]
I think the "play sound" action is actually implemented by the Add-on ToneQuilla (by the same author Kent James who retired fro Add-on development a while ago). I have converted ToneQuilla to be compatible with Thunderbird 60 and a conversion to Thunderbird 68 is planned next.

**Comment by sometimegithubuser** [comment]
You are right. I stand corrected. And it's fantastic that you have taken toneQuilla on too.

To support your work I have purchased a Pro license and will continue to renew it. As a one-time programmer (now sys admin), I understand the time it takes to create, maintain, and support software products. Please accept my, and my wife (who will be forever grateful when toneQuilla works again) sincere thank you for your work on these Addons.

Happy Holidays and a very Happy New Year to you and yours.

- Justus

**Comment by RealRaven2000** [comment]
> You are right. I stand corrected. And it's fantastic that you have taken toneQuilla on too.
> 

Yes I figured it is very similar in its functionality to FIltaQuilla, who's conversion for 68 was problematic. I think transferring the new patterns from one to the other shouldn't be impossible.

> To support your work I have purchased a Pro license and will continue to renew it. 

Thanks - I presume this is for quickFilters (which is also an Add-on that works with filters)?

> As a one-time programmer (now sys admin), I understand the time it takes to create, maintain, and support software products. Please accept my, and my wife (who will be forever grateful when toneQuilla works again) sincere thank you for your work on these Addons.
> 
> Happy Holidays and a very Happy New Year to you and yours.
> 
>     * Justus

thanks, same to you my friend!
