### ISSUE TITLE
Tb68 - Print command prints wrong message

### ISSUE THREAD

**Issue by TimRude** [RealRaven2000/FiltaQuilla#40]
FiltaQuilla version 2.0 running on TB 68.3.1 (Windows 32-bit).

If the text of an existing message (call it Message A) happens to be selected when a new message (call it Message B) arrives and gets processed by a filter which contains the FiltaQuilla Print action, the heading of the printout shows the info for Message B but the content of the printout is the selected text from Message A.

**Comment by RealRaven2000** [comment]
Is this still the case with version 2.1.2 which is online at ATN now?

**Comment by TimRude** [comment]
Sorry for the delay in replying. Had to wait to get back to the office this morning to try it on the machine still running TB68.

Yes, it still happens with 2.1.2.

**Comment by CarloMiroglio** [comment]
Same issue for me, I have version 3.0.3 running on  TB 78.8.1 (32 bit).
Thanks for support.

**Comment by RealRaven2000** [comment]
Is this still a problem? I believe many printing problems have been resolved, I am currently starting to work on printing attachments. Please reopen this issue if you feel it is necessary.
