### ISSUE TITLE
Support mix of AND and OR filter rules

### ISSUE THREAD

**Issue by CoSoCo** [RealRaven2000/FiltaQuilla#47]
Hi,
would it be possible to mix AND and OR filter rules, optionally by help of parentheses?

**Comment by RealRaven2000** [comment]
For this, have a read of the following Thunderbird bug first:
https://bugzilla.mozilla.org/show_bug.cgi?id=297852

in short: the engine would support it but they cannot be stored or edited at the moment. I think storing is probably trivial enough, but building a simple UI in thunderbird is actually much harder. I definitely think it should be supported by Thunderbird itself and not by an Add-on.

**Comment by RealRaven2000** [comment]
Closing as duplicate of #113 - lets work on getting this on Thunderbird Core's radar again!
