### ISSUE TITLE
Mac - FQ not appearing in TB 68.3 or 68.4

### ISSUE THREAD

**Issue by tuckfoot** [RealRaven2000/FiltaQuilla#49]
Mac OS 10.11.6  Thunderbird 68.4.1 or previous v68.
After restart, TBird shows FQ extension in the AddOns list, but it is not present to use.

**Comment by RealRaven2000** [comment]
> Mac OS 10.11.6 Thunderbird 68.4.1 or previous v68.
> After restart, TBird shows FQ extension in the AddOns list, but it is not present to use.

"present" - I interpret this as not in the Add-on Options popup menu: 

![image](https://user-images.githubusercontent.com/6314674/72225891-7d27c380-3582-11ea-9eec-97dd20a0ddcb.png)
(screenshot from Tb 68.3.1)


I can make a test version with a configurable button for its settings. It's frustrating that you cannot open the dialog with a command line (I think on firefox this was possible). I will see what I can do.

**Comment by mr-mmmmore** [comment]
Same here, I'm on a Mac with TB 68.7.0, the Add-on Options menu is empty.

Also, the Header Regex Match has stopped working, I think after I upgraded to 68.6.0 (I don't know the previous version I had).

**Comment by RealRaven2000** [comment]
please re-test with 2.1.2 and re-open this bug if needed

**Comment by mr-mmmmore** [comment]
I am now using version 78.9 and the menu still doesn't show...

**Comment by RealRaven2000** [comment]
> I am now using version 78.9 and the menu still doesn't show...

In my current Add-ons for Tb78 ([including FiltaQuilla 3.1](https://quickfilters.quickfolders.org/fq-versions.html#3.1)) I am using the latest version of John Bieling's WindowListener API - which puts the options of experimental API Add-ons into the Add-ons Manager:

![image](https://user-images.githubusercontent.com/6314674/114174108-11243e80-9930-11eb-867e-c027793093c6.png)
