### ISSUE TITLE
Feature Request: Play Soundfile

### ISSUE THREAD

**Issue by totalschaden** [RealRaven2000/FiltaQuilla#52]
Feature Request: Ability to Play Soundfiles as Filter Action, currently I have to use Execute file, linked to a .bat which starts vlc with soundfile

**Comment by RealRaven2000** [comment]
This is part of ToneQuilla, see:
https://github.com/RealRaven2000/ToneQuilla/issues/2

**Comment by RealRaven2000** [comment]
So I think we are going to deal with the bug on the  [ToneQuilla](https://github.com/RealRaven2000/ToneQuilla) project,
