### ISSUE TITLE
JavaScript error in filtaquilla-util.js

### ISSUE THREAD

**Issue by lsteeger** [RealRaven2000/FiltaQuilla#54]
**JavaScript error:** chrome://filtaquilla/content/filtaquilla-util.js, line 642: ReferenceError: window is not defined

**Name** 	Thunderbird
**Version** 	68.3.1
**Build ID** 	20191226074321
**User Agent** 	Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Thunderbird/68.3.1
**OS** 	Linux 5.4.6-2-MANJARO

**Comment by RealRaven2000** [comment]
Thanks for reporting. It only happens on startup (at the end of the firstRun checker) so it doesn't actually cause any malfunctions, but the line itself is superfluous, so I  have taken it out for the next version.

**Comment by eyalroz** [comment]
I'm also encountering this, and it is quite annoying!

>  It only happens on startup 

But you do a lot quite a bit of startups when debugging. Has there been a release with this fixed?

**Comment by RealRaven2000** [comment]
> I'm also encountering this, and it is quite annoying!
> 
> > It only happens on startup
> 
> But you do a lot quite a bit of startups when debugging. Has there been a release with this fixed?

which version are you running? Thunderbird 68.11 still have the update bug. I was on my dads PC earlier today and it showed up as incompatible and could not be force-updated. Had to remove and reinstall. Current version is 2.11.2

**Comment by RealRaven2000** [comment]
what version of FiltaQuilla?

**Comment by eyalroz** [comment]
Umm, version 2.0.
