### ISSUE TITLE
Options dialog disappeared under TB74

### ISSUE THREAD

**Issue by Y0tsuya** [RealRaven2000/FiltaQuilla#58]
Just upgraded to TB74 and the options menu disappeared, plus the filters don't work anymore.  Can't go back to 68 because it's incompatible with the new profile.  Checked the Error Console and don't see anything specific to FiltaQuilla.

**Comment by martinvilu** [comment]
Hello.
I have the same problem but i do see a error on the console:

`1584016316852	addons.webextension.filtaquilla@mesquilla.com	WARN	Loading extension 'filtaquilla@mesquilla.com': Reading manifest: Warning processing legacy: An unexpected property was found in the WebExtension manifest.`

**Comment by RealRaven2000** [comment]
If you like playing with beta versions, I hope you had a backup of your profile. Thunderbird 74 is in no way ready for running most Add-ons. going to take a good while to rewrite the Add-ons; legacy is deprecated for the next ESR. I will like need a few weeks to release my Add-ons as "web experiments". I would advice _strongly_ to at least wait until Tb74 is officially released and pushed to the public, unless you want to stop using Add-ons for a few months.

**Comment by Y0tsuya** [comment]
I installed 74 by accident while trying to get another add-on working.  But now I can't go back until I find out what it changed in my profile because 68 won't read it.  I'm stuck with 74.

**Comment by RealRaven2000** [comment]
try to open with the command line parameters 
-purgecaches
and
--allow-downgrades

**Comment by Y0tsuya** [comment]
The parameters don't help.  Thanks though.  Looks like I'm stuck without filters for a while.  Also seems my TB changed to 74 a few weeks ago as part of auto update.  I just clicked OK without thinking much.  It's problematic for them to push out addon-breaking updates this way.

**Comment by RealRaven2000** [comment]
> Also seems my TB changed to 74 a few weeks ago as part of auto update

this is unlikely unless you were using the beta versions. 68 is not auto-updating for 2 or 3 months because 74 is simply not there yet. The upgrade to 68 (which was "ready" in September) was rolled out slowly in November. I don't see why the next version would be rushed like this especially since the changes for Add-ons are enormous.

**Comment by Y0tsuya** [comment]
I may have been on a beta update channel.  My backup files from last week are not compatible with 68 and I have no recollection of installing a beta TB, so probably happened many months ago and I just didn't notice.  Need to pay attention next time.  Kind of sucks though.

**Comment by RealRaven2000** [comment]
Resolved here: #65 (No options box)
basically you need to use the Thunderbird main menu, details are described there..
Current releases on ATN:
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/2.1.2
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/3.0.2.0
