### ISSUE TITLE
FiltaQuilla is incompatible with Thunderbird 68.8.0

### ISSUE THREAD

**Issue by lelyveld** [RealRaven2000/FiltaQuilla#59]
Plugin is disabled and marked incompatible after upgrade to Thunderbird 68.8.0

**Comment by RealRaven2000** [comment]
It is compatible, there is a bug in Thunderbird that sometimes prevents updates from being seen. Just do a seach for Filtaquilla and force to install over.
closing Issue as invalid.

**Comment by lelyveld** [comment]
Perfect. Apologies for the bad report.

**Comment by RealRaven2000** [comment]
> Perfect. Apologies for the bad report.

No worries, it's always good to document problems better than being unsure about it.

by the way, here is the related Thundebird bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1574183
