### ISSUE TITLE
Possible to set important message flags

### ISSUE THREAD

**Issue by mwpowellhtx** [RealRaven2000/FiltaQuilla#60]
Hello, not sure if this is even possible, or if possibly `FiltaQuilla` is the correct forum to mention this at all... When I receive `IMAP` messages, say from `gmail`, so many of the messages are marked _"important"_. I would like to setup some sort of _filter_ and/or _action_ to set all messages as unimportant upon arrival in my _thunderbird inbox_. Is it possible to start with? Is this the correct forum? Thanks so much...

**Comment by RealRaven2000** [comment]
should be possible:

![image](https://user-images.githubusercontent.com/6314674/83575431-5bc27680-a527-11ea-9253-58a9b8242b4e.png)

**Comment by mwpowellhtx** [comment]
Ah @RealRaven2000 "Priority" is what they are calling it. Appreciate it. Thanks!
