### ISSUE TITLE
Not working after migration

### ISSUE THREAD

**Issue by Henkex76** [RealRaven2000/FiltaQuilla#63]
I moved my roaming-folder to a new computer (Windows server 2016) with freshly installed Thunderbird (68.10.0). After this my filters (save attachment and Launch file) doesn't work. I've removed the extension and installed again but same problem. The filters run but nothing happens. 
Can it be some old config remaining because I get the same filter settings when re-installing the add-on as before indicating that the configuration remains.

**Comment by RealRaven2000** [comment]
It depends what kind of non-standard actions / conditions you have added as conditions. One place to configure this is in FiltaQuilla's Add-on settings dialog:
![image](https://user-images.githubusercontent.com/6314674/86821220-075c6a80-c082-11ea-8c08-c3f887504c25.png)

If you have filters using any of these, you must enable them in FiltaQuilla and restart Thunderbird.

**Comment by Henkex76** [comment]
Thank you but that I have checked. I have also un-checked everything. Deleted the filters. Restarted Thunderbird. Configured FiltaQuilla with the wanted filter actions. Created new filters in Thunderbird. Still doesn't work. I can't figure out what's wrong. Never any problem prior to the migration of the server :(


> It depends what kind of non-standard actions / conditions you have added as conditions. One place to configure this is in FiltaQuilla's Add-on settings dialog:
> 
> If you have filters using any of these, you must enable them in FiltaQuilla and restart Thunderbird.

**Comment by Henkex76** [comment]
Tried to delete every trace of FiltaQuilla and re-install. Still it found my settings. Do you know where they're stored? 
Also I wanted to test the Debug function in FiltaQuilla but couldn't find any documentation on how to see the results.

**Comment by RealRaven2000** [comment]
> Tried to delete every trace of FiltaQuilla and re-install. Still it found my settings. Do you know where they're stored?
go to config editor (Tb options, advanced, bottom right)

![image](https://user-images.githubusercontent.com/6314674/87242947-57904f80-c429-11ea-8ced-6106a1bd1464.png)


Delete or reset all settings of the name:
`extensions.filtaquilla.`

> Also I wanted to test the Debug function in FiltaQuilla but couldn't find any documentation on how to see the results.

all debug options write additional log lines to the standard log. Open the log with Ctrl+Shift+J or Tools / Developer Tools / Error console.

**Comment by Henkex76** [comment]
Thank you! Debug shows some errors that might give a hint to the problem but I don't know what to make of it. 
I get a lot of "Ignoring unrecognized chrome manifest directive 'overlay'."
I also get "ReferenceError: window is not defined"

I've uninstalled Filtaquilta so many times now. Deleting all config traces. Installing again and still not working.

**Comment by RealRaven2000** [comment]
Can you leave the actual log text here? You should reset it after starting up thunderbird so it's cleaner, then start some filter operation.

I have seen "Ignoring unrecognized chrome manifest directive 'overlay'."" which is just a glitch in Thunderbird 68 and nothing too drastic (just foreshadowing the XUL overlays going away in the future, from Tb78 onwards)

The biggest question is whether you may have used unconfigured action / condition from FQ on one of your filters.
Can you run any  filter manually? You could export everything, delete the filters and then just import one (or a handfuil) to see if they work.

Also if you have quickFilters you might try the "troubleshooting" button:

![image](https://user-images.githubusercontent.com/6314674/87347562-59eaca80-c54b-11ea-9df6-820908007ace.png)

**Comment by HanttaW** [comment]
Not sure if related to this #63

Windows 10, TB 32bit.
FiltaQuilla 2.0.

After update TB 68.8.1 --> 68.10.0
Filtaquilla does not load/work. TB original quick filter toolbar has replaced it.

So far I have tried to
* switch on / off (Filter Actions / search terms)
* remove extension and reinstall it
with no success.

Below in image only warning/error that can be seen in console:
![image](https://user-images.githubusercontent.com/68318261/87509952-4cccf900-c67b-11ea-806b-5927d35fb944.png)

Please give any instructions and I´m happy to give more info (Note: my skills are limited =) )

**Comment by RealRaven2000** [comment]
Please try this prerelease:

[filtaquilla-2.1pre3.zip](https://github.com/RealRaven2000/FiltaQuilla/files/4924836/filtaquilla-2.1pre3.zip)

(you need to unpack the addon to disk and then drag into extensions - github doesn't allow uploading the xpi file directly)

**Comment by RealRaven2000** [comment]
Closing as resolved with the following releases:
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/2.1.2  (Tb 68)
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/3.0.2.0  (Tb 78)
