### ISSUE TITLE
No options box

### ISSUE THREAD

**Issue by nhpackard** [RealRaven2000/FiltaQuilla#65]
I do not see new filter actions (e.g. "remove tag").

[Filtaquilla web page](https://github.com/RealRaven2000/FiltaQuilla/issues/) tells me
```
...You can selectively enable and disable the various filter actions and search terms in the Addons Options dialog (Tools/Addons, select Extensions section, then select the Options box on the FiltaQuilla addon)...
```
But I see no "Option box" or any way to activate filter actions.

Using TB 68.11.0 on mac OS X 10.14.6.

**Comment by RealRaven2000** [comment]
If you do not have a "main menu" in Thunderbird, you can use the hamburger menu (usually top right, three horizontal lines):

![image](https://user-images.githubusercontent.com/6314674/89991669-09ff4080-dc7c-11ea-9e45-1ad19b648aff.png)

- click on Add-ons.

![image](https://user-images.githubusercontent.com/6314674/89991708-1aafb680-dc7c-11ea-91e6-40882c50904d.png)

- click on Filtaquilla.

**Comment by RealRaven2000** [comment]
Looks like the only way in Tb78.5.1 at the moment is to use the tools item from the main menu (on top). In windows, you can invoke this (even if you have the main menu hidden) from the Thunderbird window with the key combination Alt+T or F10

![image](https://user-images.githubusercontent.com/6314674/101780598-a6343980-3aee-11eb-8b0f-fd8d89399723.png)

Closing as resolved with the following release:
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/3.0.2.0
