### ISSUE TITLE
FEATURE REQUEST: filter for everything that doesn't fit any other filter

### ISSUE THREAD

**Issue by johndoe1969** [RealRaven2000/FiltaQuilla#68]
I would like to see a feature that puts everything that doesn't match one of my filters into a JUNK folder.

This is really useful for the RSS feature of Thunderbird but could also be applied to spam/junk emails.
The logic would roughly be IF matches filter(s) then apply rules, ELSE put everything that DOESN'T match filter(s) into JUNK.
You could then comb through the JUNK folder to see if something was missed and/or you need to tweak a filter rule.

I call it an INVERSE function because I use another program that let's you set up filters for RSS feeds. ie. the stuff you want to see. But it has a check box labelled: INVERSE FUNCTION. If you check that then have your filter rule(s) set to DELETE, then it will delete anything that doesn't match your filter.

**Comment by victorengel** [comment]
Can't you do this by simply having all incoming emails go to the junk folder and then apply your filters there?

**Comment by JBigglesworth** [comment]
I found appending 'Stop Filter Execution' actions on 'specific' filters with various 'catch all' filters following them (ie all 'specifics' followed by all 'catch-alls' at the end of the filter) worked for me. 

It doesn't solve everything and I've had to use tags in a couple of places but this 'bailing out' approach seems to systematically handle the bulk of my sorting needs.

The one thing I still don't quite understand is how Tbird works wrt moving mail with status=junk into the junk folder.  How/when does Tbird recognise and/or react to a filter action setting a message's status to junk?

**Comment by johndoe1969** [comment]
Interesting...however, it's too many individual tweaks to maintain in order to get it perfect. tt-rss has an option for an INVERSE MATCH, which when applied with filters only let's through what you're looking for. Granted you really gotta dial-in your filters, but once you do, you get exactly what you want. Some feeds I subscribe to have hundreds of articles a day and I may only want to see 2 or 3 of them based on content. So I really try to narrow down what I want and filter out the rest. I know I know, first world problems!!!!
