### ISSUE TITLE
Run a Program Issue

### ISSUE THREAD

**Issue by irodemo** [RealRaven2000/FiltaQuilla#71]
Hello I am unable to use the Run command filter using quickfilters on Thudrbird 68.x

Appreciate support.

**Comment by RealRaven2000** [comment]
> 
> 
> Hello I am unable to use the Run command filter using quickfilters on Thudrbird 68.x
> 
> Appreciate support.

ok what do you want to do exactly? Do you want to create a new filter (using the assistant) that does a "run" (filtaquilla) command? For this you need to create a custom template.

![image](https://user-images.githubusercontent.com/6314674/94014969-2bd40300-fda4-11ea-90ee-cb94939e2ede.png)

- right-click the assistant button to quickly get into quickFilters settings
- go to the _Advanced_ tab, enable custom templates and click on _Create New..._
![image](https://user-images.githubusercontent.com/6314674/94015082-4c03c200-fda4-11ea-956a-679c6df8bc21.png)
- enter a new name for the template (e..g "runtest")
- in the Actions box, you should be able to select the "run" command (provided FQ is configured to show it)
![image](https://user-images.githubusercontent.com/6314674/94015233-7f465100-fda4-11ea-965d-bf9a9dd42b67.png)

once you save this template it will show up as a choice in the filter assistant. note that by default quickFitlers will also add the action "move to folder" if it is triggered by the user moving a mail to a folder.

**Comment by 9930i** [comment]
I think what we are looking for is the option "Run Program" option under "Perform these actions". as we wish to run script. I too don't see this option in Thunderbird for Ubuntu, where as the same is available in Thunderbird for Windows.

Please help.
![Screenshot from 2020-10-24 22-57-10](https://user-images.githubusercontent.com/64702167/97088113-4ec83000-164c-11eb-9700-c96784962810.png)

**Comment by RealRaven2000** [comment]
Thanks for the screenshot. I will investigate but I need to revive my old Ubuntu VM to give you a definite answer. Currently very very busy converting my commercial Add-ons to Thunderbird 78.

**Comment by 9930i** [comment]
Thanks for a quick response.

Thanks

Dhruv Shah
Co-Founder
(9930i) OEPP Innovation Pvt. Ltd.
+91-9326435756

**Comment by RealRaven2000** [comment]
> Thanks for a quick response. Thanks Dhruv Shah Co-Founder (9930i) OEPP Innovation Pvt. Ltd. +91-9326435756

Could you test the latest prerelease from here?
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/3.0pre51

**Comment by RealRaven2000** [comment]
Closing as resolved with the following release:
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/3.0.2.0
