### ISSUE TITLE
repeated Printout problem / printout empty if 2nd action is included

### ISSUE THREAD

**Issue by Moerkman** [RealRaven2000/FiltaQuilla#73]
Goal: I want to print out an email as soon as it arrives

Problem: The Filter prints out the mail again and again, whenever the Filter checks for new mails .

Solution, that didn't work:
- Telling the filter to move the mail to a different folder (or changing the status from "unread" to "read" and only printing the "unread") after the printout lead to an empty printout.

Any suggestions? Thank you very much in advance!!

**Comment by RealRaven2000** [comment]
I believe this one was fixed in the meantime, if not please reopen
