### ISSUE TITLE
XPI  3.0pre12 is missing _locales/

### ISSUE THREAD

**Issue by elhennig** [RealRaven2000/FiltaQuilla#74]
In order to be able to install the beta version the files _locales/*/messages.json are missing in the xpi file.
For example I the dir from another addon and added it to the xpi:
_locales/
├── de-DE
│   └── messages.json
├── en
│   └── messages.json
├── es
│   └── messages.json
├── fr-FR
│   └── messages.json
└── ru-RU
    └── messages.json

**Comment by RealRaven2000** [comment]
> In order to be able to install the beta version the files _locales/*/messages.json are missing in the xpi file.
> For example I the dir from another addon and added it to the xpi:

Looks like the build job (revision.bat) which somebody else contributed hasn't picked them up. This one really goes over my head and even caught me out with the version number, so I will return to the old batch job format instead for the next prerelease. On top of that, the conditions and tag fields need to be rewritten (without xbl) I spent a whole day yesterday wondering how to get rid of bindings.xml, it's a tough one.

**Comment by RealRaven2000** [comment]
Closing as resolved with the following release:
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/3.0.2.0
