### ISSUE TITLE
Detach Attachments To not working

### ISSUE THREAD

**Issue by pjem7** [RealRaven2000/FiltaQuilla#76]
Hi, testing now "Detach Attachments To" feature in TB 78, Windows, FiltaQuilla 3 and it does not work.

Attachment stays unchanged in message.

![mail](https://i.imgur.com/81MPn3Z.png)

When I enable logging, log entry is done:

`[02/12/2020, 21:21:41] Applied filter "Detach" to message from "xxx" <xxx> - xxx at 05/11/2022, 18:43:44 Detach Attachments To`

but nothing is done with the attachment in the message.

**Comment by RealRaven2000** [comment]
Ok I will test this week and fix soon!

**Comment by RealRaven2000** [comment]
I was working on this for a while and posted test versions - but on the wrong github:

[filtaquilla-3.0pre48.zip](https://github.com/RealRaven2000/FiltaQuilla/files/5658858/filtaquilla-3.0pre48.zip)

The older versions were making an empty file and showed an exception in error console. I have changed the log entry if the attachment has been previously removed (detached) and show the original location of the already detached attachment. (As the data is physically missing, this is the best I can do)

```
FiltaQuilla 11:12:29.337  [0 ms]   
Attachment for 'Filta-attach test' from  2020-12-6 22:30 was already removed from mail - last seen at this location:
file:///E:/Dev/Mozilla/Dev/FiltaQuilla/test/detach/revision-1.txt?part=1.2
FiltaQuilla 11:12:29.337  [0 ms]   
Attachment for 'Filta-attach test' from  2020-12-6 22:30 was already removed from mail - last seen at this location:
file:///E:/Dev/Mozilla/Dev/FiltaQuilla/test/detach/icon128x128-1.png?part=1.3
```

**Comment by RealRaven2000** [comment]
Closing as resolved with the following releases:
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/2.1.2 (minus the nicer logging in Tb78)
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/3.0.2.0

**Comment by pjem7** [comment]
Great, thank you very much.
