### ISSUE TITLE
Make FiltaQuilla compatible with Thundebird 68.10

### ISSUE THREAD

**Issue by BrnvrlUoeey** [RealRaven2000/FiltaQuilla#77]
Tried to install FiltaQuilla to see if it would check nasty DNS inside hyperlinks but got message "not compatible with Thunderbird 68.10 (on Ubuntu 16.04).

**Comment by RealRaven2000** [comment]
> Tried to install FiltaQuilla to see if it would check nasty DNS inside hyperlinks but got message "not compatible with Thunderbird 68.10 (on Ubuntu 16.04).

Which version? The one currently on ATN (Filtaquilla 2.1.1) is compatible  with the old version of Thunderbird:
https://addons.thunderbird.net/en-US/thunderbird/addon/filtaquilla/

my latest test versions here on github are compatible with THhunderbird 78.* only - Mozilla changed the format, dropped the legacy flag.

**Comment by BrnvrlUoeey** [comment]
Retrying i successfully installed FiltaQuilla 2.0 version from 13 december 2019 (filtaquilla-2.0.xpi).
But the latest version (as a file named "filtaquilla-2.1.1-tb.xpi") is refused on installation with message "(...) not compatible with Thunderbird 68.10" whether by file install or clicking the install button on web add-ons interface. I admit my OS is getting old.

**Comment by RealRaven2000** [comment]
> Retrying i successfully installed FiltaQuilla 2.0 version from 13 december 2019 (filtaquilla-2.0.xpi).
> But the latest version (as a file named "filtaquilla-2.1.1-tb.xpi") is refused on installation with message "(...) not compatible with Thunderbird 68.10" whether by file install or clicking the install button on web add-ons interface. Which could be explained by what you said. I admit my OS is getting old .

Thanks for flagging this - apparently there was a syntax error in manifest.json which was't caught... I fixed this and uploaded 2.1.2 which is currently awaiting review. I will also have to re-upload 3.0 as a new version (which I just had pushed this afternoon) because the queue only sees one version at a time :(

**Comment by RealRaven2000** [comment]
Closing as resolved with the following release:
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/2.1.2
