### ISSUE TITLE
Subject Regex Help

### ISSUE THREAD

**Issue by ondohotola** [RealRaven2000/FiltaQuilla#82]
I have tested the following regex on the following subject line (copied/pasted) in regex101.com 
where it succeeds but in TBird 78.5.1 with Filtaquilla 3.0.3 it does not save the Attachments

Regex:
    EX\w{4}\.\d{4}\ DR\ EW\ LISSE\ \-\ BATCH\d{4}

Subject:
    EXPSEM.1317 DR EW LISSE - BATCH1317

If I separate this into different conditions (ie looking individually for EX and DR EW LISSE - BATCH)
it does find the messages and saves the attachments.

I have ticked 'Subject Regex Match' in the Add-On FiltaQuilla Prefs.

Any advice?

el

**Comment by RealRaven2000** [comment]
Just in case there is a problem with whitespace characters, try this:

`EX\w{4}.\d{4}\sDR\sEW\sLISSE\s-\sBATCH\d{4}`
