### ISSUE TITLE
FiltaQuilla 3.0.3 on TB78 issue (save attachment)

### ISSUE THREAD

**Issue by liquid64** [RealRaven2000/FiltaQuilla#85]
I was really excited to see support be added for TB78, however, I'm running into an issue.  On my inbox (IMAP, if that's important, with roughly 17K emails in the inbox), after creating the filter to match on a specific email address, and selecting "save attachment to", after I receive any new messages, the filter begins processing my entire inbox (roughly 3 years worth of emails).  In my destination folder, I begin seeing attachments from emails that are the oldest in my inbox (roughly 3 years old).  Thunderbird slows down to a crawl, and the only way to fix it, is to go into message filters, uncheck the filter, close and reopen TB.  I never clicked the "run now" button at any time, and only have "manual and "getting new mail" selected in my filter.  This behavior only seems to happen when using the "save attachment to" action, although I haven't tested any other of the FiltaQuilla actions.

**Comment by RealRaven2000** [comment]
I think Thunderbird decides which filters it's going to run - the FiltaQuilla Add-on has no influence on which filters it decides to run and which not. As a workaround, could you change the condition to  "unread mails" only?

**Comment by liquid64** [comment]
Thanks for the reply. I did try that, but TB is still running through all of the emails in the inbox (meaning Thunderbird slows to a crawl, and the "spinny circle" keeps spinning).  This time at least, with "status = unread" it isn't saving the old attachments.  I wonder if this could be an issue where the "run now" function is somehow triggered by TB.  The obvious answer is to clean up my inbox though.  Thank you for your help.

**Comment by RealRaven2000** [comment]
> Thanks for the reply. I did try that, but TB is still running through all of the emails in the inbox (meaning Thunderbird slows to a crawl, and the "spinny circle" keeps spinning). This time at least, with "status = unread" it isn't saving the old attachments. I wonder if this could be an issue where the "run now" function is somehow triggered by TB. The obvious answer is to clean up my inbox though. Thank you for your help.

Did reindexing help? I am trying to tidy up the bugs database, still have 16 issues related to attachments... just trying to weed out the duplicates and the ones that have been resolved.

**Comment by liquid64** [comment]
Thanks for checking back.  Reindexing didn't help, however, I figured out that if I select "Filter After Junk Classification", the filter behaved correctly.  If "Filter Before Junk Classification" was selected, if was someone going through every email.  I'm guessing that's unrelated to your extension.  I've just never run into that before.

**Comment by RealRaven2000** [comment]
> Thanks for checking back. Reindexing didn't help, however, I figured out that if I select "Filter After Junk Classification", the filter behaved correctly. If "Filter Before Junk Classification" was selected, if was someone going through every email. I'm guessing that's unrelated to your extension. I've just never run into that before.

Ok, that workaround is also documented elsewhere, and [I have plenty](https://github.com/RealRaven2000/FiltaQuilla/issues?q=is%3Aissue+is%3Aopen++attachment%23+in%3Atitle+) (at least 15) -  so I am going to close this one if that's ok!
