### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by xlovinglyx** [RealRaven2000/FiltaQuilla#87]
_

**Comment by xlovinglyx** [comment]
Please look at it diabolus or raven.

**Comment by xlovinglyx** [comment]
Very important, the script should collect all my email accounts & try to detect them BEFORE @,
excluding the domain & extention .. .

ex:

i can have two accounts in yandex, they can look like:

lola@ya.ru
or
lola@yandex.com
or
lola@yandex.ru

only the part "lola" is to verify.

Thanks

**Comment by RealRaven2000** [comment]
If it is urgent, you should check with [cardbook](https://addons.thunderbird.net/thunderbird/addon/cardbook/?src=search), I think he has some such filtering capacities built in, I was talking to Phillipe about his Add-on on the last developers call. The address book is a big field, and on top of AB lookup you got a very specific new condition "not appearing in to field". I think it might better to turn it around and have condition like this:

`[My Identities] - [contains] - [To]` - this way you would have a single condition (identities) and then possibly add different flavors ([to], [cc], [from]) on the right hand side.

**Comment by xlovinglyx** [comment]
it's not urgent, i just like your word on it that u'll implement it. no need to direct me to a totally different addon
with functions I never needed.... .

**Comment by xlovinglyx** [comment]
ps: i can do it myself, if i want, adding my account in the to field, so ur way of resuming it is a bit indirect.

my wish again: making the addon detect my accounts & filter upon every account names excluding @ & what follows..
since email account domains can be sometimes written differently. please dont shorten requests to utter simplicity.

**Comment by xlovinglyx** [comment]
A gift:

because you don't want to understand & keep wanting users who explain u several times & in clear words
that your regex codes do not involve "ANYTHING" as i wanted.. even by photos because simplistic language is not enough
or u block issues like the 75, here is your present, "images"...

RealRaven: "at the moment it just means any character . 0, once or multiple times ?. Which feels kind of redundant,"

1) it's a test regex, not an expectation. just to see if it was working in ur extention.
2) nothing's redundant if, like i already explained a million times, ANYTHING should be
around lolita(2numbers). was expected. emptiness can be anything too, cause it's a choice,
like characters.



i reminded u:

"\s matches whitespace (spaces, tabs and new lines).
\S matches anything but a whitespace"

which means that your proposal doesn't fit the expected result, as it could be ANYTHING,
around lolita(2numbers), & ur \s or \S doesn't include characters, numbers, etc etc.

then u wanted me to use dots instead of that: .?
so i'll show u again by creating (ur fetish reports:scanned "images"of results
either involving your . (without question mark, as u wanted......)
& using ur \s and your \S too.

Strangely, i realized that Raven:
"May I ask why you need the .? characters around it? If it needs to be part of a sequence of other characters surrounding the search pattern, maybe \S (non whitespace character) might be a better fit." this may work with or without \s
using: lolita\d{2} /gm

But im still sceptical, because in gmailui addon that involved regex filtering, i found instants where lolita
alone in the regex wasnt found between strange characters.thats why i keep using .? & not /S

As you can see,not working, as the first lolita wasn't detected.
![x1](https://user-images.githubusercontent.com/53103638/128946390-9eea7f50-cbca-4c9c-9e1f-e68c18101295.png)

working:
![x2](https://user-images.githubusercontent.com/53103638/128946466-b0e63554-82cb-4178-953a-ce7ce7341324.png)

the strange one, i still believe some strange characters would defeat this simple regex without .?
![x3](https://user-images.githubusercontent.com/53103638/128946559-ffbc8cca-7094-4a02-84dd-59b1c0fa08df.png)

**Comment by RealRaven2000** [comment]
if it was not detected 4 times but only 3 (in the the same email body) it
may be down to greedy/nongreedy matching.  doesn't  matter because the
regex test just tests true (found at least once) or false  (not found at
all).

there is no example where none are found.

**Comment by xlovinglyx** [comment]
"if it was not detected 4 times but only 3 (in the the same email body) it may be down to greedy/nongreedy matching. doesn't matter because the regex test just tests true (found at least once) or false (not found at all)."

wrong, if my stupid email contained that lolita77 on the first line & nowhere else, i'd be FKD.
& i don't want such examples to arrive.

& no example where none are found because i'd take me hours to test many spam emails
to risk finding that example as i did in the past.

**Comment by RealRaven2000** [comment]
> wrong, if my stupid email contained that lolita77 on the first line & nowhere else, i'd be FKD.
> & i don't want such examples to arrive.

prove it? delete the other lines / occurences and show me its not found
![image](https://user-images.githubusercontent.com/6314674/129065373-c03a212d-ffb3-4da4-878c-ba08ce80f29c.png)

`.?` does exactly the same in this case:
![image](https://user-images.githubusercontent.com/6314674/129065539-cd803dc0-9205-463c-90bf-5cb69302c064.png)

because `.?` means ANYTHING or NOTHING. `anything`XXX or XXX need to be matched. what case exactly does `.?` exclude?

Remember we are not counting occurences here we just say "is  pattern found at least once". That's what `Regex.test()` in FiltaQuilla does

**Comment by xlovinglyx** [comment]
https://github.com/RealRaven2000/FiltaQuilla/issues/87#issuecomment-886053429

5 months passed & it's taking forever..

even if it's not urgent, it's something i'd need to use in a fixed set & forget way.
but are you even going to add it ? because asking me if it's urgent & ignoring it
during 5 months could also lead to you to ignore it forever ((

**Comment by xlovinglyx** [comment]
****

**Comment by xlovinglyx** [comment]
.. .
