### ISSUE TITLE
options missing

### ISSUE THREAD

**Issue by rustyconc** [RealRaven2000/FiltaQuilla#89]
Cannot access Add-on options from the 3 dot menu?
TB 78.6.0 (32-bit)
FQ filtaquilla-3.0.3-tb.xpi
![Screenshot 2021-01-05 23 38 28](https://user-images.githubusercontent.com/29746675/103726474-622e3a80-4faf-11eb-83f7-af4485c4c1ad.png)

**Comment by pv-65** [comment]
Same issue with 78.6.0esr(64-bit) on debian bullseye.

**Comment by pv-65** [comment]
same issue observed on 78.5.1(64-bit) on debian bullseye.

**Comment by RealRaven2000** [comment]
There is currently no options screen that is content script compatible. The options are in a xhtml dialog which cannot be integrated with this method of loading options - But you can open options through tools / add-on options / FiltaQuilla, which gives access to most more complicated legacy Add-ons that have recently been converted into experiments:

![image](https://user-images.githubusercontent.com/6314674/103757624-f11b7100-5008-11eb-8649-c1f8b2662f6e.png)

I will add the "help wanted" if there are any devs out there who would like to rewrite the options to be content tab compliant.

**Comment by rustyconc** [comment]
Thanks! I had looked for that alternate route, and it was not available.  Turns out "Add-on Options" is only a menu item in the Tools menu if you enable the standard Menu bar.  It is not available through the single common menu.

**Comment by RealRaven2000** [comment]
> Thanks! I had looked for that alternate route, and it was not available. Turns out "Add-on Options" is only a menu item in the Tools menu if you enable the standard Menu bar. It is not available through the single common menu.

They must have removed it, that's bad news. I was pretty sure it used to be in a `>` chevron beside the Add-ons entry.

**Comment by Glandos** [comment]
Same issue with Thunderbird 78.8.0 from Debian:

https://user-images.githubusercontent.com/297578/111142605-29997700-8585-11eb-9eaf-93490fefed3a.mp4

**Comment by RealRaven2000** [comment]
As of [version 3.1](https://quickfilters.quickfolders.org/fq-versions.html#3.1), you can now access FiltaQuilla from the 3 dot menu:

![image](https://user-images.githubusercontent.com/6314674/111152068-38355d80-8588-11eb-9128-d434bd11ab69.png)

I am using John Bieling's Window Loader experimental API and he updated it to be more conform with other Add-ons from Thunderbird 78 going forward. Same change will be applied to all my Add-ons, so eventually the Tools / Add-ons menu is going away. (We can't have both ways).
