### ISSUE TITLE
Actions missing

### ISSUE THREAD

**Issue by balusam** [RealRaven2000/FiltaQuilla#90]
When I opened Filter menu on Kubuntu 20.10 TB 78.5.0 (64-bit) there are no filtaquilla actions. 

![Screenshot_20210109_205639](https://user-images.githubusercontent.com/32707882/104105216-b0984d80-52bd-11eb-8fa4-7ba7f1c17aaf.png)

**Comment by RealRaven2000** [comment]
I see at least one:  "Launch File". 
Check the tools menu for FiltaQuilla Add-ons settings:
![image](https://user-images.githubusercontent.com/6314674/104105432-f2b59500-52a5-11eb-83c1-3507636b3080.png)

if you see duplicates in the actions, just restart Thunderbird (Thunderbird is not good at removing existing items from there)

**Comment by woolfie** [comment]
Thunderbird 78.6.1 running in Linux doesn't have the "Tools->Add-on Options" menu.

https://support.mozilla.org/en-US/kb/thunderbird-add-ons-frequently-asked-questions#w_how-do-i-configure-add-ons says to access the add-on options from within Thunderbird's add-on manager, however FiltaQuilla (3.0.3) doesn't list "options" in the three dot menu:

![filtaquilla-three-dots](https://user-images.githubusercontent.com/967287/105897154-d162e180-5fe5-11eb-8c71-17b05a0801f0.jpg)

**Comment by RealRaven2000** [comment]
It's not there - try to enable the main menu for Thunderbird (it's on top!). That's currently the only place you can access "mail extensions with experimental APIs" from. To make the menu visible, you can right-click the main toolbar and select "menu bar":
![image](https://user-images.githubusercontent.com/6314674/105898679-a3939200-6011-11eb-8f52-ce5b646b3b0b.png)

This is the menu bar:
![image](https://user-images.githubusercontent.com/6314674/105898720-af7f5400-6011-11eb-913b-9d55468455ba.png)

On Mac and with some Linux distros / settings this main menu is always displayed at the very top of the screen. In Windows you can use the ALT key to access the accelerators for this menu, e.g/ ALT+T for Tools. Not sure if that works on Linux though.

**Comment by iago-lito** [comment]
Well, I've got the same issue here. My menu does not even show the "Launch  File":

![pb_filtaquilla](https://user-images.githubusercontent.com/10091387/117321888-ce517a00-ae8d-11eb-9657-0dc5d5539c5d.png)

And there is no `FiltaQuilla` entry in `Tools -> Add-on Options`

![no_menu](https://user-images.githubusercontent.com/10091387/117322036-ede8a280-ae8d-11eb-8747-ad700d47b2b8.png)

.. although the extension seems up to date (thunderbird 78.10.0, FiltaQuillla 3.1)

![activated](https://user-images.githubusercontent.com/10091387/117322166-0ce73480-ae8e-11eb-9ac5-150678b25759.png)

What could be wrong ? :(

**Comment by RealRaven2000** [comment]
try this version. Mozilla keeps breaking shit.

[filtaquilla-3.2pre6.zip](https://github.com/RealRaven2000/FiltaQuilla/files/6437569/filtaquilla-3.2pre6.zip)

to install download the zip file. drag the zip file into Thunderbird Add-ons manager. you should see this:

![Uploading image.png…]()

**Comment by iago-lito** [comment]
Arh, this must be really annoying :\ Thank you for this file. I do see the new `options` button now, and the filters are back. I'll check behaviour for a few days and come back if anything seems cheesy again :)

Thank you for FiltaQuilla <3
