### ISSUE TITLE
Detach, then move reattaches

### ISSUE THREAD

**Issue by victorengel** [RealRaven2000/FiltaQuilla#92]
I tried out FiltaQuilla because I need a solution to save space in my IMAP account. The Detach Attachments To function seemed to work fine. I tried it out by first moving emails to a local folder, then running the Detach Attachments To function. Then moving the emails back to the account. This last step seems to have moved the attachments back as attachments, so the net effect is zero. Is this the intended functionality? Maybe there's a different way to do what I want? I want attachments to be saved offline locally and removed from the IMAP server but retain the email.

**Comment by RealRaven2000** [comment]
Hah, that may be a problem with IMAP not syncing the "detachment". Remember Tb would have to re-upload the mail to the IMAP server, I am not sure the filter action is currently capable of doing that. I will look into it of course. I mean you will still save the space locally as long as you don't move the mail.

**Comment by victorengel** [comment]
OK - I've revised my process. Now it goes like this: 

- In Gmail, select all messages with attachments and size, say > 10 MB.
- Apply a label in gmail.
- In Thunderbird, create a local folder, say 10MBPlusLocal.
- Move all messages from the folder created to match gmail's label to the local folder. (this copies the messages locally, but the messages are still on gmail - that is what I was missing)
- In Gmail, do the same selection again. Can't select by label added previously, because the move removed the label.
- In Gmail, delete the messages in the selection.
- In Thunderbird, run the tool to detach all attachments.
- In Thunderbird, create a folder in the gmail account called Had10MB.
- In Thunderbird, move messages from which attachments were detached to Had10MB.

Now the messages are on gmail, they show attachments, but they are not accessible, because they've been detached.

Issue (should I create a new issue for this): this skips inline attachments. It is possible to do the same thing manually with inline attachments by first View, Message Body as Plain Text. Then detach all attachments. This does not work with the FiltaQuilla detach method. It's be great if it could be fixed to do this.

One other huge convenience want: - if the file already exists, currently, the tool has the option to create a new file by appending a serial number. I have a duplicate cleaner that can clean this up later, but it would be great if the tool added another step: if the file already exists, compare it to the attachment. If the existing file is identical to the attachment, detach it without saving (it's already there). This happens a lot when people reply to emails and include the attachments. The same attachment is being sent back and forth.

**Comment by RealRaven2000** [comment]
The best workaround for removing attachments is to use it in combination with the "Move Later" action.
