### ISSUE TITLE
Feature Request: Add ToneQuilla functionality to FiltaQuilla

### ISSUE THREAD

**Issue by sometimegithubuser** [RealRaven2000/FiltaQuilla#94]
I really miss ToneQuilla's ability to add a sound to filters. MailBoxAlert can be used for a tone per folder, but the ability to have a filter action to play a sound is really helpful. 

Would it be possible to add a "play a sound" filter action to FiltaQuilla or upgrade ToneQuilla for TB 78+?

**Comment by RealRaven2000** [comment]
Here is a first test version - only tested with mp3 files - took a while to make this work. There will probably be a UI added for enabling / disabling this feature in options

[filtaquilla-3.1pre8.zip](https://github.com/RealRaven2000/FiltaQuilla/files/5960733/filtaquilla-3.1pre8.zip)

To install, download the zip file and drag into Thunderbird Add-ons Manager. It should automatically unpack the shipped mp3 files into profile/extensions/filtaquilla - but you can of course conigure it to use sound files from other locations.

![image](https://user-images.githubusercontent.com/6314674/107557675-d45af600-6bd1-11eb-902d-03d98a24b020.png)

There is no preview / play button at the moment.

**Comment by pwright2b** [comment]
Very interested in seeing this happen.

**Comment by sometimegithubuser** [comment]
I'm impressed - such quick work to have a test version. Thank you!

I installed the 3.1pre8 version and added a sound to a filter using one of the supplied MP3 files. I then tested a couple of incoming mails. It worked as expected with the message filtering and playing the selected MP3.

Unfortunately all the sound files we've been using are WAV, so I can't test any of them. 

I look forward to the next update!

**Comment by RealRaven2000** [comment]
> I installed the 3.1pre8 version and added a sound to a filter using one of the supplied MP3 files. I then tested a couple of incoming mails. It worked as expected with the message filtering and playing the selected MP3.
> 
> Unfortunately all the sound files we've been using are WAV, so I can't test any of them.

Well the code for playing wav files is in there, what happens if you select a wav file?

**Comment by sometimegithubuser** [comment]
Alex,

Sorry, I misunderstood and thought that only MP3s were implemented, so that's all I tested. And they worked perfectly. 

I just tested a .WAV and no sound is played. So .WAV is not working.

**Comment by RealRaven2000** [comment]
Another test version, including some wav files and tested:

[filtaquilla-3.1pre16.zip](https://github.com/RealRaven2000/FiltaQuilla/files/5966149/filtaquilla-3.1pre16.zip)

To install, download the zip file and drag into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
I added an option to the window so this feature is not enabled by default:

[filtaquilla-3.1pre20.zip](https://github.com/RealRaven2000/FiltaQuilla/files/5972722/filtaquilla-3.1pre20.zip)

To make the action visible enable the checkbox in conditions:
![image](https://user-images.githubusercontent.com/6314674/107788677-99c79980-6d48-11eb-837b-6091112f2fa8.png)

**Comment by fade2gray** [comment]
I can spot typos, `ToneQilla` / `TonQuilla` 😲😁

**Comment by RealRaven2000** [comment]
> I can spot typos, `ToneQilla` / `TonQuilla`

Fixed - and added l10n for the label in the dropdown too:
[filtaquilla-3.1pre24.zip](https://github.com/RealRaven2000/FiltaQuilla/files/5973227/filtaquilla-3.1pre24.zip)

**Comment by sometimegithubuser** [comment]
The option works. I enabled it and "Play Sound" is offered as a filter choice. I disabled it and the choice is gone. And sounds work.

**Comment by RealRaven2000** [comment]
released 3.1 with the new feature

**Comment by black-puppydog** [comment]
I'm honestly a bit confused right now. Shouldn't the reference to ToneQuilla be removed if it's not a dependency any longer?

**Comment by RealRaven2000** [comment]
> I'm honestly a bit confused right now. Shouldn't the reference to ToneQuilla be removed if it's not a dependency any longer?

the reference where?

**Comment by black-puppydog** [comment]
From memory: I installed FiltaQuilla, tried to get the audio filter action enabled, and it said sth like "play sound (ToneQuilla)".

Then I started searching for TQ, found the repo, found the note that I should check with FQ instead, got confused, posted here, decided to just try it anyhow, and it worked. :)
So I think somewhere there might be a string left-over. :P

**Comment by black-puppydog** [comment]
https://github.com/search?l=JSON&q=%22%28tonequilla%29%22&type=Code

Jup, in the translation files.
(Ctrl-F `(Tone`)

**Comment by RealRaven2000** [comment]
> https://github.com/search?l=JSON&q=%22%28tonequilla%29%22&type=Code
> 

ok, I think it might have been meant as a back-reference (it works without ToneQuilla). the main problem is that Thunderbird / FF cannot play mp3 files (anymore?) so I converted everything to ogg to avoid having to ship these large wav files...

**Comment by RealRaven2000** [comment]
(So I might remove the reference to ToneQuilla for the next version)

**Comment by black-puppydog** [comment]
Yeah no big deal of course, just thought I'd point it out. :)
