### ISSUE TITLE
Feature Request: Add selected emails domain names to a particular filter

### ISSUE THREAD

**Issue by anishmittal2020** [RealRaven2000/FiltaQuilla#96]
## Use case

I have a filter which has many domain names such as `@xyz.com`, that filters out any emails from the particular domain, and store it in local Spam folder. This is useful as many Spam emails are from the same domain name. 

## Request

It will be nice if a list of selected email address (or domain names) can be appended to filter of our choice with the same existing criterias.

**Comment by RealRaven2000** [comment]
> ## Use case
> I have a filter which has many domain names such as `@xyz.com`, that filters out any emails from the particular domain, and store it in local Spam folder. This is useful as many Spam emails are from the same domain name.
> 
> ## Request
> It will be nice if a list of selected email address (or domain names) can be appended to filter of our choice with the same existing criterias.

I may be wrong but, I think this would be more of a request for my filter management tool [quickFilters](https://addons.thunderbird.net/thunderbird/addon/quickfilters/). One way to achieve that would be by building a custom template that automatically appends your domain list (and can do other things, like add the email / domain / subject of the current mail / manually moved mail to the filter. The idea is once you set up the template you can just recall it whenever you create a new filter through the assistant.
