### ISSUE TITLE
Printing in background should not enable global setting 'print.always_print_silent' permanently

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/FiltaQuilla#97]
When a filter executes the "print" action, it sets printing in background as a permanent setting. It should only print in background but restore the previous settings of `print.always_print_silent`. I guess this would be usually false, by default.

See also:
https://github.com/cleidigh/printing-tools-ng/issues/26

**Comment by RealRaven2000** [comment]
Here is a test version:

[filtaquilla-3.1pre29.zip](https://github.com/RealRaven2000/FiltaQuilla/files/6036181/filtaquilla-3.1pre29.zip)

To install, download the zip file and drag into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
It has been pointed out that FiltaQuilla clears the user setting as soon as it starts (not just when print action from a filter is triggered). Here is a patched version:

[Uploading filtaquilla-3.1pre30.zip…]()

To install, download the zip file and drag into Thunderbird Add-ons Manager.

**Comment by cleidigh** [comment]
the zip link above does not appear to work

**Comment by RealRaven2000** [comment]
> the zip link above does not appear to work

Sorry, I didn't notice - must have been a file transfer problem (our Internet is pretty spotty at the moment) - here we go again:

[filtaquilla-3.1pre31.zip](https://github.com/RealRaven2000/FiltaQuilla/files/6043591/filtaquilla-3.1pre31.zip)
